------------------------------------------------------------------------------
--	PolarMerge.lua
--	Two variants (mutually exclusive):
--	1. Pangaea Embrace (active): Two arms from pangea ends toward map edge
--	2. Arctic Merge (commented out): Single V-shaped landmass from edge


-- Final Target Spec - implement in steps - its complicated - build sequentially on top of each other
-- PANGEA EMBRACE (Arctic Merge Variant - shares file for mutual exclusivity)

-- Shape:
-- Two continental arms extending from pangea ends toward map edge
-- Creates large enclosed or semi-enclosed area between arms
-- Heavy mountain ridges along arms

-- Location:
-- North or south map edge
-- Map wraps X-wise, Y-end is edge of map
-- Arms connect to pangea at its eastern and western extremes

-- Arm Positioning:
-- Flexible placement, rough guidelines:
-- Arms generally span majority of pangea width
-- Minimum gap between arms: 20% of pangea width
-- Arms don't need to reach all the way to center

-- Structure:

-- Western Arm:
-- Extends from western pangea toward map edge
-- Curves eastward along map edge
-- Width: 1-8 tiles, varies gradually along length
-- Generally thickens toward map edge (not always)

-- Eastern Arm:
-- Extends from eastern pangea toward map edge
-- Curves westward along map edge
-- Width: 1-8 tiles, varies gradually along length
-- Generally thickens toward map edge (not always)

-- Arm Connection:
-- When arms are close together near map edge, they sometimes fully touch
-- Creates full enclosure (minus gaps cut later)
-- Not always connected, variable

-- Mountain Ridges:
--  Heavy mountain presence along arms
-- Irregular ridge running along north/south progression of each arm
-- Ridge positioning flexible within arm (can be left side, right side, or center)
-- Amount and distribution varied between map generations
-- No specific count or gap distance, organic placement
-- Creates strong visual ridge line along arm length

-- Ocean Gaps:
-- Gap definition: Full horizontal cut through arm with water tiles
-- Minimum water thickness: 1 tile, frequently 2-3 tiles
-- Cut direction: Roughly horizontal (imperfect, not straight)
-- Connects inner sea area to outer ocean
-- Minimum 1 gap always present
-- Often 2 or 3 gaps
-- Higher numbers (4+) possible, gradually less likely
-- Gaps not always clean or perfect cuts
-- Gaps can merge or be far apart
-- Position: Generally close to map edge (2-3 tiles off literal edge)

-- Terrain:
-- Arms:
-- Adjacent to mountains: Hills 80%
-- 2nd tile from mountains: Hills 65%
-- 3rd+ tile from mountains: Hills 50%
-- Coastal edges: Flat 90% (takes precedence over mountain-adjacency hills)

-- Starting Positions:
-- Entire landmass generated by this script: Ineligible for player starting positions
-- City-state starting positions: Eligible

-- Variation:
-- North or south map edge
-- Arm widths vary gradually (1-8 range)
-- Arm positioning flexible within 20% minimum gap constraint
-- Arms may or may not connect at map edge
-- Gap count: Minimum 1, often 2-3, 4+ rare but possible
-- Gap water thickness: 1-3 tiles
-- Mountain ridge positioning varies within arms
-- Mountain amount and distribution varies between generations

-- Placement:
-- Must connect to pangea at both eastern and western ends
-- Must approach or touch map edge'

------------------------------------------------------------------------------
include("X_IslandHelpers");

------------------------------------------------------------------------------
-- CONFIG: All tunables in one place. Change here to control behavior.
------------------------------------------------------------------------------
local CONFIG = {
	-- Placement
	EMBRACE_ODDS = 100,  -- 0-100: chance to attempt Pangaea Embrace when this type is drafted

	-- Phase 1: Arm shape
	ARM_WIDTH_MAX_INLAND = 7,  -- cap width at 7 when 4+ tiles from edge (toward pangea)
	ARM_WIDTH_MIN = 4, ARM_WIDTH_RANGE = 4,  -- armLen = 4-7 (can expand toward edge later)
	ARM_WIDTH_AT_PANGEA_MIN = 3,
	THICKEN_TOWARD_EDGE_PCT = 80,  -- % of maps where arms thicken toward edge (else thin)
	SOFTER_CURVE_PCT = 40,  -- % of maps with gentler arm curvature
	GENTLER_FREQ_PCT = 50,  -- % of maps with lower curve frequency (less wavy)
	CURVE_AMP_VARIATION_PCT = 20,  -- per-arm ±% from base amp (correlated but not mirror)

	-- Phase 2: Terrain (gradient by distance to ridge, coastal overrides)
	HILLS_PCT_MIN = 50,  -- global floor: never >50% flat
	HILLS_PCT_ADJ = 80, HILLS_PCT_2ND = 65, HILLS_PCT_3RD = 50,  -- by distance to ridge
	COASTAL_FLAT_PCT = 50,  -- coastal thick: max 50% flat (capped by HILLS_PCT_MIN)
	COASTAL_THIN_WIDTH = 3,
	THIN_STRIP_HILLS_PCT = 70,
	RIDGE_WIDTH_THRESHOLD = 4,
	RIDGE_3_TILE_PCT = 35, RIDGE_4_TILE_PCT = 12,
	RIDGE_POSITIONS = 3,
	RIDGE_SECTION_COUNT = 4,  -- partition arm into sections for mountain % variation
	RIDGE_RIFT_COUNT_MIN = 2, RIDGE_RIFT_COUNT_MAX = 5,  -- fewer rifts = more mountain by default
	RIDGE_RIFT_HEIGHT_MIN = 1, RIDGE_RIFT_HEIGHT_MAX = 3,
	RIDGE_RIFT_IS_WATER = true,
	RIDGE_RIFT_HILLS_PCT = 70,
	HEAVY_RIDGE_PCT = 18,  -- heavy thick ridge, several thin water gaps close together
	HEAVY_RIDGE_RIFT_COUNT_MIN = 4, HEAVY_RIDGE_RIFT_COUNT_MAX = 7,
	HEAVY_RIDGE_RIFT_HEIGHT = 1,  -- thin gaps only

	-- Phase 3: Ocean gaps (water cuts through arms)
	GAP_POLICY = "always",
	GAP_OPTIONAL_PCT = 60,
	GAP_COUNT_MIN = 2, GAP_COUNT_MAX = 5,  -- 2-5 gaps, more frequent
	GAP_THICKNESS_MIN = 1, GAP_THICKNESS_MAX = 4,  -- min width when not cutting full; unused if GAP_CUT_FULL_WIDTH
	GAP_CUT_FULL_WIDTH = true,
	GAP_SPLINTER_PCT = 70,  -- % of gaps that zigzag (splintered path) instead of straight line
	GAP_SPLINTER_STEP_PCT = 28,  -- per step: % chance to move row up/down (zigzag)
	GAP_DIST_FROM_EDGE_MIN = 6, GAP_DIST_FROM_EDGE_MAX = 12,
};

local function isLand(plotTypes, x, y, iW, iH)
	if x < 0 or x >= iW or y < 0 or y >= iH then return false; end
	local t = plotTypes[y * iW + x];
	return t == PlotTypes.PLOT_LAND or t == PlotTypes.PLOT_HILLS or t == PlotTypes.PLOT_MOUNTAIN;
end

------------------------------------------------------------------------------
-- PANGAEA EMBRACE
------------------------------------------------------------------------------
local function findPangeaExtentAtEdge(plotTypes, iW, iH, southEdge, scanDepth)
	local extent = { west = iW, east = -1, maxDistFromEdge = 0 };
	local edgeY = southEdge and 0 or (iH - 1);
	for x = 0, iW - 1 do
		for d = 0, scanDepth do
			local y = southEdge and d or (edgeY - d);
			if y >= 0 and y < iH and isLand(plotTypes, x, y, iW, iH) then
				if x < extent.west then extent.west = x; end
				if x > extent.east then extent.east = x; end
				if d > extent.maxDistFromEdge then extent.maxDistFromEdge = d; end
				break;
			end
		end
	end
	return extent;
end

local function drawPangaeaEmbrace(plotTypes, iW, iH, wrapX, wrapY)
	-- wrapY maps are not supported (arms need clear N and S edges).
	if wrapY then return false; end

	-- Pick whether the arms grow from the south edge (y=0) or north edge (y=iH-1).
	-- The pangea body sits on the opposite side of the map.
	local southEdge = (Map.Rand(2, "") == 0);
	local edgeY = southEdge and 0 or (iH - 1);

	-- Scan inward from the chosen edge (up to 25 rows) to locate the pangea.
	-- Returns: extent.west/east = leftmost/rightmost pangea column found near the edge.
	--          extent.maxDistFromEdge = how many rows in from the edge the pangea starts.
	local extent = findPangeaExtentAtEdge(plotTypes, iW, iH, southEdge, 25);

	-- Need the pangea to span at least 15 columns near the edge, otherwise there
	-- is no room for two arms with a gap between them.
	local span = extent.east - extent.west;
	if span < 15 then return false; end

	-- westAnchor/eastAnchor: the outermost pangea columns near the edge.
	-- Arms root here — one growing inward from each side of the pangea's mouth.
	local westAnchor = extent.west;
	local eastAnchor = extent.east;

	local armLenW = CONFIG.ARM_WIDTH_MIN + Map.Rand(CONFIG.ARM_WIDTH_RANGE, "");
	local armLenE = CONFIG.ARM_WIDTH_MIN + Map.Rand(CONFIG.ARM_WIDTH_RANGE, "");

	-- Check that a meaningful open-sea gap remains between the two arms.
	-- seaMinX/seaMaxX are the inner edges of the west and east arms respectively.
	local seaMinX = westAnchor + armLenW;
	local seaMaxX = eastAnchor - armLenE;
	if seaMaxX <= seaMinX + 5 then return false; end

	-- armDepth: target N-S length of each arm, just enough to bridge the gap
	-- from the map edge to where the pangea was detected (+1 to ensure contact).
	-- armWidthW/E: per-arm depth cap, slightly randomised above armDepth.
	local armDepth = extent.maxDistFromEdge + 1;
	local armWidthW = math.max(3, armDepth + Map.Rand(3, ""));
	local armWidthE = math.max(3, armDepth + Map.Rand(3, ""));

	-- -------------------------------------------------------------------------
	-- PHASE 1: Paint arm land tiles.
	-- Spec: "Width: 1-8 tiles, varies gradually along length. Generally thickens
	-- toward map edge (not always)." We iterate depth (d) first; at each row,
	-- widthAtD = E-W extent, thickens from 1-2 at pangea to armLen at edge.
	-- -------------------------------------------------------------------------
	local curveAmp  = (Map.Rand(100, "") < CONFIG.SOFTER_CURVE_PCT) and (1 + Map.Rand(2, "")) or (2 + Map.Rand(2, ""));
	local curveFreq = (Map.Rand(100, "") < CONFIG.GENTLER_FREQ_PCT) and (0.2 + Map.Rand(2, "") * 0.1) or (0.4 + Map.Rand(3, "") * 0.1);
	local thickenBias = (Map.Rand(100, "") < CONFIG.THICKEN_TOWARD_EDGE_PCT) and 1 or 0;
	local v = CONFIG.CURVE_AMP_VARIATION_PCT / 100;
	local curveAmpW = curveAmp * (1 - v + Map.Rand(math.floor(v * 200) + 1, "") / 100);
	local curveAmpE = curveAmp * (1 - v + Map.Rand(math.floor(v * 200) + 1, "") / 100);

	local westTiles = {};
	local eastTiles = {};
	local allTilesSet = {};
	local maxDepth = math.max(armDepth, armWidthW, armWidthE);

	for d = 0, maxDepth - 1 do
		local y = southEdge and d or (edgeY - d);
		if y < 0 or y >= iH then break; end
		local t = (maxDepth > 1) and (d / (maxDepth - 1)) or 1;
		if thickenBias == 0 then t = 1 - t; end
		local widthAtD_W = math.max(CONFIG.ARM_WIDTH_AT_PANGEA_MIN, math.floor(CONFIG.ARM_WIDTH_AT_PANGEA_MIN + (armLenW - CONFIG.ARM_WIDTH_AT_PANGEA_MIN) * t) + Map.Rand(2, "") - 1);
		local widthAtD_E = math.max(CONFIG.ARM_WIDTH_AT_PANGEA_MIN, math.floor(CONFIG.ARM_WIDTH_AT_PANGEA_MIN + (armLenE - CONFIG.ARM_WIDTH_AT_PANGEA_MIN) * t) + Map.Rand(2, "") - 1);
		widthAtD_W = math.min(armLenW, widthAtD_W);
		widthAtD_E = math.min(armLenE, widthAtD_E);
		if d >= 4 then
			widthAtD_W = math.min(CONFIG.ARM_WIDTH_MAX_INLAND, widthAtD_W);
			widthAtD_E = math.min(CONFIG.ARM_WIDTH_MAX_INLAND, widthAtD_E);
		end

		for w = 0, widthAtD_W - 1 do
			local baseX = westAnchor + w;
			local x = baseX + math.floor(curveAmpW * math.sin(d * curveFreq));
			if wrapX then x = ((x % iW) + iW) % iW; end
			if x < 0 or x >= iW then break; end
			if isLand(plotTypes, x, y, iW, iH) then break; end
			local key = y * iW + x;
			if not allTilesSet[key] then
				westTiles[#westTiles + 1] = {x, y};
				allTilesSet[key] = true;
			end
		end

		for w = 0, widthAtD_E - 1 do
			local baseX = eastAnchor - w;
			local x = baseX - math.floor(curveAmpE * math.sin(d * curveFreq));
			if wrapX then x = ((x % iW) + iW) % iW; end
			if x < 0 or x >= iW then break; end
			if isLand(plotTypes, x, y, iW, iH) then break; end
			local key = y * iW + x;
			if not allTilesSet[key] then
				eastTiles[#eastTiles + 1] = {x, y};
				allTilesSet[key] = true;
			end
		end
	end

	-- -------------------------------------------------------------------------
	-- PHASE 2: Terrain. Ridge = mountain (variable position: outer/center/inner).
	-- Thicker arms: ridge is 2 tiles; variable placement per arm.
	-- -------------------------------------------------------------------------
	local westMinX, westMaxX = {}, {};
	local eastMinX, eastMaxX = {}, {};
	for _, t in ipairs(westTiles) do
		local x, y = t[1], t[2];
		if not westMinX[y] or x < westMinX[y] then westMinX[y] = x; end
		if not westMaxX[y] or x > westMaxX[y] then westMaxX[y] = x; end
	end
	for _, t in ipairs(eastTiles) do
		local x, y = t[1], t[2];
		if not eastMinX[y] or x < eastMinX[y] then eastMinX[y] = x; end
		if not eastMaxX[y] or x > eastMaxX[y] then eastMaxX[y] = x; end
	end

	local ridgePosW = Map.Rand(CONFIG.RIDGE_POSITIONS, "");
	local ridgePosE = Map.Rand(CONFIG.RIDGE_POSITIONS, "");

	local function getRidgeWidth(w)
		local base = 1 + Map.Rand(2, "");
		local widthBias = (w >= 6 and Map.Rand(100, "") < 25) and 1 or 0;
		if w >= 8 and Map.Rand(100, "") < 12 then widthBias = widthBias + 1; end
		return math.min(w, base + widthBias);
	end
	local function isRidgeWest(x, y)
		local lo, hi = westMinX[y], westMaxX[y];
		if not lo then return false; end
		hi = hi or lo;
		local w = hi - lo + 1;
		local ridgeW = math.min(getRidgeWidth(w), w);
		local start = (ridgePosW == 0) and lo or (ridgePosW == 1) and (lo + math.floor((w - ridgeW) / 2)) or (hi - ridgeW + 1);
		return x >= start and x < start + ridgeW;
	end
	local function isRidgeEast(x, y)
		local lo, hi = eastMinX[y], eastMaxX[y];
		if not hi then return false; end
		lo = lo or hi;
		local w = hi - lo + 1;
		local ridgeW = math.min(getRidgeWidth(w), w);
		local start = (ridgePosE == 0) and (hi - ridgeW + 1) or (ridgePosE == 1) and (lo + math.floor((w - ridgeW) / 2)) or lo;
		return x >= start and x < start + ridgeW;
	end

	local ridgeSet = {};
	for _, t in ipairs(westTiles) do
		if isRidgeWest(t[1], t[2]) then ridgeSet[t[1] .. "," .. t[2]] = true; end
	end
	for _, t in ipairs(eastTiles) do
		if isRidgeEast(t[1], t[2]) then ridgeSet[t[1] .. "," .. t[2]] = true; end
	end

	local heavyRidge = (Map.Rand(100, "") < CONFIG.HEAVY_RIDGE_PCT);
	local riftCountMin = heavyRidge and CONFIG.HEAVY_RIDGE_RIFT_COUNT_MIN or CONFIG.RIDGE_RIFT_COUNT_MIN;
	local riftCountMax = heavyRidge and CONFIG.HEAVY_RIDGE_RIFT_COUNT_MAX or CONFIG.RIDGE_RIFT_COUNT_MAX;
	local riftHeightMin = heavyRidge and CONFIG.HEAVY_RIDGE_RIFT_HEIGHT or CONFIG.RIDGE_RIFT_HEIGHT_MIN;
	local riftHeightMax = heavyRidge and CONFIG.HEAVY_RIDGE_RIFT_HEIGHT or CONFIG.RIDGE_RIFT_HEIGHT_MAX;

	local function buildRiftRows(tiles)
		local rows = {};
		for _, t in ipairs(tiles) do rows[t[2]] = true; end
		local rowList = {};
		for y in pairs(rows) do rowList[#rowList + 1] = y; end
		table.sort(rowList);
		if #rowList < 2 then return {}; end
		local riftRowSet = {};
		local nSec = CONFIG.RIDGE_SECTION_COUNT;
		local secSize = math.max(1, math.floor(#rowList / nSec));
		local secWeights = {};
		for s = 1, nSec do
			secWeights[s] = 0.5 + Map.Rand(11, "") / 10;
		end
		local totalWeight = 0;
		for s = 1, nSec do totalWeight = totalWeight + secWeights[s]; end
		local numRifts = riftCountMin + Map.Rand(riftCountMax - riftCountMin + 1, "");
		numRifts = math.min(numRifts, math.max(1, #rowList - 1));
		local clusterCenter;
		if heavyRidge and #rowList >= 3 then
			clusterCenter = rowList[1 + Map.Rand(#rowList, "")];
		end
		for _ = 1, numRifts do
			local y;
			if clusterCenter then
				local offset = Map.Rand(5, "") - 2;
				y = clusterCenter + offset;
				y = math.max(rowList[1], math.min(rowList[#rowList], y));
			else
				local r = Map.Rand(math.floor(totalWeight * 100), "") / 100;
				local acc = 0;
				local sec = 1;
				for s = 1, nSec do
					acc = acc + secWeights[s];
					if r < acc then sec = s; break; end
				end
				local loIdx = 1 + (sec - 1) * secSize;
				local hiIdx = (sec < nSec) and (sec * secSize) or #rowList;
				local pickIdx = loIdx + Map.Rand(math.max(1, hiIdx - loIdx + 1), "") - 1;
				y = rowList[math.min(pickIdx, #rowList)];
			end
			y = math.max(rowList[1], math.min(rowList[#rowList], y));
			local h = riftHeightMin + Map.Rand(riftHeightMax - riftHeightMin + 1, "");
			for dy = 0, h - 1 do
				riftRowSet[y + dy] = true;
			end
		end
		return riftRowSet;
	end
	local westRiftRows = buildRiftRows(westTiles);
	local eastRiftRows = buildRiftRows(eastTiles);

	for _, t in ipairs(westTiles) do
		local idx = t[2] * iW + t[1];
		if isRidgeWest(t[1], t[2]) then
			if westRiftRows[t[2]] then
				plotTypes[idx] = CONFIG.RIDGE_RIFT_IS_WATER and PlotTypes.PLOT_OCEAN
					or ((Map.Rand(100, "") < CONFIG.RIDGE_RIFT_HILLS_PCT) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND);
			else
				plotTypes[idx] = PlotTypes.PLOT_MOUNTAIN;
			end
		end
	end
	for _, t in ipairs(eastTiles) do
		local idx = t[2] * iW + t[1];
		if isRidgeEast(t[1], t[2]) then
			if eastRiftRows[t[2]] then
				plotTypes[idx] = CONFIG.RIDGE_RIFT_IS_WATER and PlotTypes.PLOT_OCEAN
					or ((Map.Rand(100, "") < CONFIG.RIDGE_RIFT_HILLS_PCT) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND);
			else
				plotTypes[idx] = PlotTypes.PLOT_MOUNTAIN;
			end
		end
	end

	local distToRidge = {};
	local queue = {};
	for k in pairs(ridgeSet) do
		local x, y = k:match("([^,]+),([^,]+)");
		x, y = tonumber(x), tonumber(y);
		distToRidge[k] = 0;
		queue[#queue + 1] = {x, y};
	end
	local q = 1;
	while q <= #queue do
		local x, y = queue[q][1], queue[q][2];
		local key = x .. "," .. y;
		local d = distToRidge[key] or 0;
		for dir = 1, 6 do
			local nx, ny = GetHexNeighbor(x, y, dir, iW, iH, wrapX, wrapY);
			if nx >= 0 and nx < iW and ny >= 0 and ny < iH and allTilesSet[ny * iW + nx] then
				local nk = nx .. "," .. ny;
				if distToRidge[nk] == nil then
					distToRidge[nk] = d + 1;
					queue[#queue + 1] = {nx, ny};
				end
			end
		end
		q = q + 1;
	end

	local function isCoastal(x, y)
		for dir = 1, 6 do
			local nx, ny = GetHexNeighbor(x, y, dir, iW, iH, wrapX, wrapY);
			if nx >= 0 and nx < iW and ny >= 0 and ny < iH then
				if not allTilesSet[ny * iW + nx] and plotTypes[ny * iW + nx] == PlotTypes.PLOT_OCEAN then
					return true;
				end
			end
		end
		return false;
	end

	for _, t in ipairs(westTiles) do
		local idx = t[2] * iW + t[1];
		if not isRidgeWest(t[1], t[2]) then
			local hillsPct = CONFIG.HILLS_PCT_3RD;
			if isCoastal(t[1], t[2]) then
				local w = westMinX[t[2]] and (westMaxX[t[2]] - westMinX[t[2]] + 1) or 0;
				hillsPct = (w >= CONFIG.COASTAL_THIN_WIDTH) and (100 - CONFIG.COASTAL_FLAT_PCT) or CONFIG.THIN_STRIP_HILLS_PCT;
			else
				local d = distToRidge[t[1] .. "," .. t[2]];
				if d == 1 then hillsPct = CONFIG.HILLS_PCT_ADJ;
				elseif d == 2 then hillsPct = CONFIG.HILLS_PCT_2ND; end
			end
			hillsPct = math.max(CONFIG.HILLS_PCT_MIN, hillsPct);
			plotTypes[idx] = (Map.Rand(100, "") < hillsPct) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND;
		end
	end
	for _, t in ipairs(eastTiles) do
		local idx = t[2] * iW + t[1];
		if not isRidgeEast(t[1], t[2]) then
			local hillsPct = CONFIG.HILLS_PCT_3RD;
			if isCoastal(t[1], t[2]) then
				local w = eastMinX[t[2]] and (eastMaxX[t[2]] - eastMinX[t[2]] + 1) or 0;
				hillsPct = (w >= CONFIG.COASTAL_THIN_WIDTH) and (100 - CONFIG.COASTAL_FLAT_PCT) or CONFIG.THIN_STRIP_HILLS_PCT;
			else
				local d = distToRidge[t[1] .. "," .. t[2]];
				if d == 1 then hillsPct = CONFIG.HILLS_PCT_ADJ;
				elseif d == 2 then hillsPct = CONFIG.HILLS_PCT_2ND; end
			end
			hillsPct = math.max(CONFIG.HILLS_PCT_MIN, hillsPct);
			plotTypes[idx] = (Map.Rand(100, "") < hillsPct) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND;
		end
	end

	-- -------------------------------------------------------------------------
	-- PHASE 3: Ocean gaps. Cut water through arms so inner sea connects to outer ocean.
	-- Policy: "always" = guaranteed, "optional" = random chance, "never" = solid arms.
	-- -------------------------------------------------------------------------
	local doGaps = (CONFIG.GAP_POLICY == "always") or
		(CONFIG.GAP_POLICY == "optional" and Map.Rand(100, "") < CONFIG.GAP_OPTIONAL_PCT);
	local numGaps = doGaps and (CONFIG.GAP_COUNT_MIN + Map.Rand(CONFIG.GAP_COUNT_MAX - CONFIG.GAP_COUNT_MIN + 1, "")) or 0;
	local distFromEdge = CONFIG.GAP_DIST_FROM_EDGE_MIN + Map.Rand(CONFIG.GAP_DIST_FROM_EDGE_MAX - CONFIG.GAP_DIST_FROM_EDGE_MIN + 1, "");
	distFromEdge = math.min(distFromEdge, math.max(0, maxDepth - 7));  -- keep >5 from edge, fit in arm

	local function cutSplinteredPath(minXByY, maxXByY, y0, stepDir)
		local lo, hi = minXByY[y0], maxXByY[y0];
		if not lo or not hi then return; end
		local x0 = stepDir > 0 and lo or hi;
		local xEnd = stepDir > 0 and hi or lo;
		local py = y0;
		for x = x0, xEnd, stepDir do
			if minXByY[py] and x >= minXByY[py] and x <= maxXByY[py] then
				local wx = wrapX and (((x % iW) + iW) % iW) or x;
				if wx >= 0 and wx < iW then
					plotTypes[py * iW + wx] = PlotTypes.PLOT_OCEAN;
				end
			end
			if Map.Rand(100, "") < CONFIG.GAP_SPLINTER_STEP_PCT then
				local ny = py + (Map.Rand(2, "") == 0 and 1 or -1);
				if minXByY[ny] and maxXByY[ny] and x >= minXByY[ny] and x <= maxXByY[ny] then
					py = ny;
				end
			end
		end
	end

	local function cutStraightRow(minXByY, maxXByY, y0)
		local lo, hi = minXByY[y0], maxXByY[y0];
		if lo and hi then
			for x = lo, hi do
				local wx = wrapX and (((x % iW) + iW) % iW) or x;
				if wx >= 0 and wx < iW then
					plotTypes[y0 * iW + wx] = PlotTypes.PLOT_OCEAN;
				end
			end
		end
	end

	for g = 1, numGaps do
		local d = southEdge and (maxDepth - 1 - distFromEdge - Map.Rand(2, "")) or (distFromEdge + Map.Rand(2, ""));
		d = math.max(0, math.min(maxDepth - 1, d));
		local y = southEdge and d or (edgeY - d);
		if y >= 0 and y < iH then
			local splinter = Map.Rand(100, "") < CONFIG.GAP_SPLINTER_PCT;
			if splinter then
				cutSplinteredPath(westMinX, westMaxX, y, 1);
				cutSplinteredPath(eastMinX, eastMaxX, y, -1);
			else
				cutStraightRow(westMinX, westMaxX, y);
				cutStraightRow(eastMinX, eastMaxX, y);
			end
		end
	end

	-- Spec: "Entire landmass generated by this script: Ineligible for player starting positions"
	_polar_pangea_excluded_plots = _polar_pangea_excluded_plots or {};
	for _, t in ipairs(westTiles) do
		local idx = t[2] * iW + t[1];
		local pt = plotTypes[idx];
		if pt == PlotTypes.PLOT_LAND or pt == PlotTypes.PLOT_HILLS or pt == PlotTypes.PLOT_MOUNTAIN then
			_polar_pangea_excluded_plots[idx + 1] = true;
		end
	end
	for _, t in ipairs(eastTiles) do
		local idx = t[2] * iW + t[1];
		local pt = plotTypes[idx];
		if pt == PlotTypes.PLOT_LAND or pt == PlotTypes.PLOT_HILLS or pt == PlotTypes.PLOT_MOUNTAIN then
			_polar_pangea_excluded_plots[idx + 1] = true;
		end
	end

	return true;
end

--[==[
------------------------------------------------------------------------------
-- ARCTIC MERGE (disabled)
------------------------------------------------------------------------------
local HILLS_ADJ = 75;
local TUNDRA_LAT = 0.85;

local function isWater(plotTypes, x, y, iW, iH)
	if x < 0 or x >= iW or y < 0 or y >= iH then return false; end
	return plotTypes[y * iW + x] == PlotTypes.PLOT_OCEAN;
end

local function getTundraLatitudeY(iH, southEdge)
	local offset = math.floor((iH / 2) * (1 - TUNDRA_LAT));
	if southEdge then return offset; end
	return iH - 1 - offset;
end

local function rippleToLand(plotTypes, startX, startY, iW, iH, wrapX, southEdge)
	local visited = {};
	local queue = {{startX, startY}};
	visited[startX .. "," .. startY] = true;
	local dist = 0;
	local maxDist = 15;
	while #queue > 0 and dist < maxDist do
		local next = {};
		for _, p in ipairs(queue) do
			local x, y = p[1], p[2];
			if isLand(plotTypes, x, y, iW, iH) then return dist, x, y; end
			for dir = 1, 6 do
				local nx, ny = GetHexNeighbor(x, y, dir, iW, iH, wrapX, false);
				if ny >= 0 and ny < iH then
					local inward = southEdge and (ny > y) or (ny < y);
					if inward then
						local key = nx .. "," .. ny;
						if not visited[key] then
							visited[key] = true;
							next[#next + 1] = {nx, ny};
						end
					end
				end
			end
		end
		queue = next;
		dist = dist + 1;
	end
	return nil, nil, nil;
end

local function findValidXForPangea(plotTypes, iW, iH, southEdge, maxScan)
	local validX = {};
	local edgeY = southEdge and 0 or (iH - 1);
	for x = 0, iW - 1 do
		for d = 1, math.min(maxScan, 12) do
			local y = southEdge and d or (edgeY - d);
			if y >= 0 and y < iH and isLand(plotTypes, x, y, iW, iH) then
				validX[#validX + 1] = x;
				break;
			end
		end
	end
	return validX;
end

local function drawArcticMerge(plotTypes, centerX, edgeY, southEdge, contactDist, startOffset, hasWaterPath, numRidges, iW, iH, wrapX, wrapY)
	local inlandSeaY = getTundraLatitudeY(iH, southEdge);
	local startY = southEdge and startOffset or (edgeY - startOffset);
	local endY = southEdge and math.min(contactDist + 2, iH - 1) or math.max(0, edgeY - contactDist - 2);

	local width = 8 + Map.Rand(5, "");
	local landTiles = {};
	local ridgeTiles = {};
	local waterPathTiles = {};
	local seaTiles = {};

	local splinterChance = 25;
	local ridge1Gaps = {};
	local ridge2Gaps = {};

	for row = 0, math.abs(endY - startY) do
		local rowY = southEdge and (startY + row) or (startY - row);
		if rowY < 0 or rowY >= iH then break; end
		local half = math.floor(width / 2);
		for dx = -half, half do
			local x = centerX + dx;
			if wrapX then x = ((x % iW) + iW) % iW; end
			if x >= 0 and x < iW then landTiles[#landTiles + 1] = {x, rowY}; end
		end
	end

	local landSet = {};
	for _, t in ipairs(landTiles) do landSet[t[1] .. "," .. t[2]] = true; end

	for row = 0, math.abs(endY - startY) do
		local rowY = southEdge and (startY + row) or (startY - row);
		if rowY < 0 or rowY >= iH then break; end
		local half = math.floor(width / 2);
		local vSpread = math.floor(half * 0.15 * (row + 1));
		local ridge1X = centerX - math.floor(half * 0.35) - vSpread;
		local ridge2X = centerX + math.floor(half * 0.35) + vSpread;
		if Map.Rand(100, "") < splinterChance then ridge1Gaps[row] = true; end
		if Map.Rand(100, "") < splinterChance then ridge2Gaps[row] = true; end
		if not ridge1Gaps[row] then
			local rx = wrapX and (((ridge1X % iW) + iW) % iW) or ridge1X;
			if rx >= 0 and rx < iW and landSet[rx .. "," .. rowY] then ridgeTiles[#ridgeTiles + 1] = {rx, rowY}; end
		end
		if numRidges >= 2 and not ridge2Gaps[row] then
			local rx = wrapX and (((ridge2X % iW) + iW) % iW) or ridge2X;
			if rx >= 0 and rx < iW and landSet[rx .. "," .. rowY] then ridgeTiles[#ridgeTiles + 1] = {rx, rowY}; end
		end
		if hasWaterPath then
			local pathX = wrapX and (((centerX % iW) + iW) % iW) or centerX;
			if pathX >= 0 and pathX < iW and landSet[pathX .. "," .. rowY] then waterPathTiles[#waterPathTiles + 1] = {pathX, rowY}; end
		end
	end

	local seaSize = 4 + Map.Rand(9, "");
	local seaRadius = math.max(1, math.floor(math.sqrt(seaSize / 3.14)));
	local seaCenterX = centerX;
	local yLo, yHi = math.min(startY, endY), math.max(startY, endY);
	local seaCenterY = math.max(yLo + 1, math.min(inlandSeaY, yHi - 1));
	if wrapX then seaCenterX = (((seaCenterX % iW) + iW) % iW); end

	for dy2 = -seaRadius, seaRadius do
		for dx2 = -seaRadius, seaRadius do
			if dx2 * dx2 + dy2 * dy2 <= seaRadius * seaRadius then
				local sx = seaCenterX + dx2;
				if wrapX then sx = (((sx % iW) + iW) % iW); end
				local sy = seaCenterY + dy2;
				if sx >= 0 and sx < iW and sy >= 0 and sy < iH and sy >= startY and (southEdge and sy <= endY or not southEdge and sy >= endY) then
					seaTiles[#seaTiles + 1] = {sx, sy};
				end
			end
		end
	end

	local landSet2 = {};
	for _, t in ipairs(landTiles) do landSet2[t[1] .. "," .. t[2]] = true; end
	local waterPathSet = {};
	for _, t in ipairs(waterPathTiles) do waterPathSet[t[1] .. "," .. t[2]] = true; end
	local seaSet = {};
	for _, t in ipairs(seaTiles) do
		seaSet[t[1] .. "," .. t[2]] = true;
		landSet2[t[1] .. "," .. t[2]] = nil;
	end

	local ridgeSet = {};
	for _, t in ipairs(ridgeTiles) do ridgeSet[t[1] .. "," .. t[2]] = true; end

	local mountainPicks = {};
	for i = 1, #ridgeTiles do mountainPicks[i] = i; end
	for i = #mountainPicks, 2, -1 do
		local j = Map.Rand(i, "") + 1;
		mountainPicks[i], mountainPicks[j] = mountainPicks[j], mountainPicks[i];
	end
	local numMountains = math.min(#ridgeTiles, 2 + Map.Rand(math.max(1, #ridgeTiles), ""));
	for i = 1, numMountains do
		local t = ridgeTiles[mountainPicks[i]];
		ridgeSet[t[1] .. "," .. t[2]] = "mountain";
	end

	local islandInSea = {};
	if seaSize >= 10 and Map.Rand(100, "") < 50 then
		local candidates = {};
		for _, t in ipairs(seaTiles) do
			local x, y = t[1], t[2];
			local adjWater = 0;
			for dir = 1, 6 do
				local nx, ny = GetHexNeighbor(x, y, dir, iW, iH, wrapX, wrapY);
				if seaSet[nx .. "," .. ny] then adjWater = adjWater + 1; end
			end
			if adjWater >= 4 then candidates[#candidates + 1] = t; end
		end
		if #candidates > 0 then
			local pick = candidates[Map.Rand(#candidates, "") + 1];
			islandInSea[pick[1] .. "," .. pick[2]] = true;
		end
	end

	local function adjToMountain(x, y)
		for dir = 1, 6 do
			local nx, ny = GetHexNeighbor(x, y, dir, iW, iH, wrapX, wrapY);
			if ridgeSet[nx .. "," .. ny] == "mountain" then return true; end
		end
		return false;
	end

	if Map.Rand(100, "") < 25 then
		for _ = 1, 1 + Map.Rand(3, "") do
			local lx = centerX + (Map.Rand(5, "") - 2);
			if wrapX then lx = (((lx % iW) + iW) % iW); end
			local ly = southEdge and Map.Rand(2, "") or (edgeY - Map.Rand(2, ""));
			if lx >= 0 and lx < iW and ly >= 0 and ly < iH then
				landTiles[#landTiles + 1] = {lx, ly};
				landSet2[lx .. "," .. ly] = true;
			end
		end
	end

	for _, t in ipairs(landTiles) do
		local x, y = t[1], t[2];
		local idx = y * iW + x;
		if seaSet[x .. "," .. y] and not islandInSea[x .. "," .. y] then
			plotTypes[idx] = PlotTypes.PLOT_OCEAN;
		elseif waterPathSet[x .. "," .. y] then
			plotTypes[idx] = PlotTypes.PLOT_OCEAN;
		elseif islandInSea[x .. "," .. y] then
			plotTypes[idx] = (Map.Rand(100, "") < 50) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND;
		elseif ridgeSet[x .. "," .. y] == "mountain" then
			plotTypes[idx] = PlotTypes.PLOT_MOUNTAIN;
		elseif adjToMountain(x, y) then
			plotTypes[idx] = (Map.Rand(100, "") < HILLS_ADJ) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND;
		else
			plotTypes[idx] = (Map.Rand(100, "") < 50) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND;
		end
	end
end
--]==]

------------------------------------------------------------------------------
-- ENTRY POINT
------------------------------------------------------------------------------
function TryPlacePolarMerge(plotTypes, opts)
	if _island_placed and _island_placed.polarmerge then return false; end
	local iW, iH = opts.iW, opts.iH;
	local wrapX = opts.wrapX or true;
	local wrapY = opts.wrapY or false;
	if wrapY then return false; end

	if Map.Rand(100, "") < CONFIG.EMBRACE_ODDS then
		if drawPangaeaEmbrace(plotTypes, iW, iH, wrapX, wrapY) then
			if not _island_placed then _island_placed = {}; end
			_island_placed.polarmerge = true;
			return true;
		end
	end
	return false;
end
