------------------------------------------------------------------------------
--	PolarMerge.lua
--	Two variants (mutually exclusive):
--	1. Pangaea Embrace (active): Two arms from pangea ends toward map edge
--	2. Arctic Merge (commented out): Single V-shaped landmass from edge


-- Final Target Spec - implement in steps - its complicated - build sequentially on top of each other
-- PANGEA EMBRACE (Arctic Merge Variant - shares file for mutual exclusivity)

-- Shape:
-- Two continental arms extending from pangea ends toward map edge
-- Creates large enclosed or semi-enclosed area between arms
-- Heavy mountain ridges along arms

-- Location:
-- North or south map edge
-- Map wraps X-wise, Y-end is edge of map
-- Arms connect to pangea at its eastern and western extremes

-- Arm Positioning:
-- Flexible placement, rough guidelines:
-- Arms generally span majority of pangea width
-- Minimum gap between arms: 20% of pangea width
-- Arms don't need to reach all the way to center

-- Structure:

-- Western Arm:
-- Extends from western pangea toward map edge
-- Curves eastward along map edge
-- Width: 1-8 tiles, varies gradually along length
-- Generally thickens toward map edge (not always)

-- Eastern Arm:
-- Extends from eastern pangea toward map edge
-- Curves westward along map edge
-- Width: 1-8 tiles, varies gradually along length
-- Generally thickens toward map edge (not always)

-- Arm Connection:
-- When arms are close together near map edge, they sometimes fully touch
-- Creates full enclosure (minus gaps cut later)
-- Not always connected, variable

-- Mountain Ridges:
--  Heavy mountain presence along arms
-- Irregular ridge running along north/south progression of each arm
-- Ridge positioning flexible within arm (can be left side, right side, or center)
-- Amount and distribution varied between map generations
-- No specific count or gap distance, organic placement
-- Creates strong visual ridge line along arm length

-- Ocean Gaps:
-- Gap definition: Full horizontal cut through arm with water tiles
-- Minimum water thickness: 1 tile, frequently 2-3 tiles
-- Cut direction: Roughly horizontal (imperfect, not straight)
-- Connects inner sea area to outer ocean
-- Minimum 1 gap always present
-- Often 2 or 3 gaps
-- Higher numbers (4+) possible, gradually less likely
-- Gaps not always clean or perfect cuts
-- Gaps can merge or be far apart
-- Position: Generally close to map edge (2-3 tiles off literal edge)

-- Terrain:
-- Arms:
-- Adjacent to mountains: Hills 80%
-- 2nd tile from mountains: Hills 65%
-- 3rd+ tile from mountains: Hills 50%
-- Coastal edges: Flat 90% (takes precedence over mountain-adjacency hills)

-- Starting Positions:
-- Entire landmass generated by this script: Ineligible for player starting positions
-- City-state starting positions: Eligible

-- Variation:
-- North or south map edge
-- Arm widths vary gradually (1-8 range)
-- Arm positioning flexible within 20% minimum gap constraint
-- Arms may or may not connect at map edge
-- Gap count: Minimum 1, often 2-3, 4+ rare but possible
-- Gap water thickness: 1-3 tiles
-- Mountain ridge positioning varies within arms
-- Mountain amount and distribution varies between generations

-- Placement:
-- Must connect to pangea at both eastern and western ends
-- Must approach or touch map edge'

------------------------------------------------------------------------------
include("X_IslandHelpers");

------------------------------------------------------------------------------
-- CONFIG: All tunables in one place. Change here to control behavior.
------------------------------------------------------------------------------
local CONFIG = {
	-- Placement
	EMBRACE_ODDS = 100,  -- 0-100: chance to attempt Pangaea Embrace when this type is drafted

	-- Arm count and anchor positioning (relative weights within tier)
	ARM_COUNT_ODDS = { [1] = 5, [2] = 90, [3] = 5 },  -- 1, 2, or 3 arms
	ARM_ANCHOR_INSET_MIN = 0, ARM_ANCHOR_INSET_MAX = 35,  -- % of span: anchors move inward from extremes (0=at extremes)
	ARM_ANCHOR_JITTER_PCT = 15,  -- each anchor can shift ±this % of span along the edge

	-- Phase 1: Arm shape
	ARM_WIDTH_MIN = 2, ARM_WIDTH_RANGE = 5,  -- armLen = 2-6 away from edge (no 1-tile arms)
	ARM_WIDTH_AT_PANGEA_MIN = 1,
	ARM_WIDTH_1_TILE_ALLOW_PCT = 5,  -- when row would be 1-tile wide, only 5% keep it; 95% bump to 2
	ARM_WIDTH_MAX_INLAND = 6,  -- cap inland (d>=4) at 6
	EDGE_EXPAND_ROWS = 3,  -- last N rows can expand quickly toward armLen
	EDGE_EXPAND_PCT = 45,  -- % of maps where edge expands
	MERGE_GAP_THRESHOLD = 6,  -- when gap between arms <= this, allow merge at edge
	MERGE_PCT = 35,  -- % of maps where arms merge when close
	THICKEN_TOWARD_EDGE_PCT = 80,  -- % of maps where arms thicken toward edge (else thin)
	SOFTER_CURVE_PCT = 25,  -- % of maps with gentler curvature
	GENTLER_FREQ_PCT = 45,  -- % of maps with lower curve frequency
	CURVE_AMP_VARIATION_PCT = 12,  -- per-arm ±% from base amp (reduced extremes)

	-- Phase 2: Terrain (gradient by distance to ridge, coastal overrides)
	HILLS_PCT_MIN = 50,  -- global floor: never >50% flat
	HILLS_PCT_ADJ = 80, HILLS_PCT_2ND = 65, HILLS_PCT_3RD = 50,  -- by distance to ridge
	COASTAL_FLAT_PCT = 90,  -- thick coastal only: 90% flat per spec
	COASTAL_THIN_WIDTH = 5,  -- only rows 5+ tiles wide get flat; thin/snakey strips keep hills for settlement
	THIN_STRIP_HILLS_PCT = 70,
	RIDGE_WIDTH_THRESHOLD = 4,
	RIDGE_3_TILE_PCT = 35, RIDGE_4_TILE_PCT = 12,
	RIDGE_POSITIONS = 3,
	RIDGE_SECTION_COUNT = 4,
	RIDGE_RIFT_COUNT_MIN = 1, RIDGE_RIFT_COUNT_MAX = 3,  -- fewer rifts = mostly mountain, tight pathways
	RIDGE_RIFT_HEIGHT_MIN = 1, RIDGE_RIFT_HEIGHT_MAX = 1,  -- always 1 row = tight naval pathways
	RIDGE_RIFT_IS_WATER = true,
	RIDGE_RIFT_HILLS_PCT = 70,
	RIDGE_RIFT_CLUSTER_PCT = 35,  -- % of rifts that become cluster: 3-4 row band with 2 small paths, mountains between
	RIDGE_RIFT_CLUSTER_BAND_ROWS = 4,
	RIDGE_RIFT_CLUSTER_NUM_PATHS = 2,
	RIDGE_RIFT_CLUSTER_PATH_TILES_MIN = 1, RIDGE_RIFT_CLUSTER_PATH_TILES_MAX = 2,
	HEAVY_RIDGE_PCT = 32,  -- more maps: thick ridge with several thin water gaps (tricky pathways)
	HEAVY_RIDGE_RIFT_COUNT_MIN = 3, HEAVY_RIDGE_RIFT_COUNT_MAX = 5,
	HEAVY_RIDGE_RIFT_HEIGHT = 1,
	SPLINTERED_RIDGE_PCT = 30,  -- thick 4-6 tile ridge, many 1-tile water gaps clustered (splintered cliffs/water)
	SPLINTERED_RIDGE_WIDTH_MIN = 4, SPLINTERED_RIDGE_WIDTH_MAX = 6,
	SPLINTERED_GAP_COUNT_MIN = 6, SPLINTERED_GAP_COUNT_MAX = 14,
	SPLINTERED_GAP_2_TILE_PCT = 25,  -- 25% chance each gap extends to 2 tiles
	RIDGE_THIN_EXPAND_ROWS = 2,  -- after this many 1-tile rows, try to expand
	RIDGE_THIN_EXPAND_PCT = 85,  -- chance to expand to 2 tiles when thin stretch detected
	RIDGE_THIN_FORCE_AT = 5,     -- force expansion when 5+ consecutive 1-tile rows (avoids snakey flimsy ridges)
	ARM_STRAIGHT_FORCE_AT = 5,   -- if same thickness 5 rows in a row, force change (smaller or bigger) on 5th

	-- Arctic fill: land between arms near map edge (becomes snow later)
	-- Within map: rows 1-4 from edge, max row 4. Non-contiguous (row 3 only possible).
	-- Across maps: 20% get extended band (small X area) where rows 5-6 allowed.
	-- Horizontal: depth (tall/short) varies by column.
	ARCTIC_FILL_EDGE_EXTEND_ROWS = 2,  -- extra rows of polar land from edge (makes polar cap extend further down)
	ARCTIC_FILL_8_ROW_PCT = 50,       -- 50%: edge protrusion goes up to 8 rows off the edge
	ARCTIC_FILL_DEPTH_MIN = 1, ARCTIC_FILL_DEPTH_MAX = 5,  -- per-column: 1-5 rows (max row 4)
	ARCTIC_FILL_EXTENDED_MAP_PCT = 20,   -- 20% of maps get extended band
	ARCTIC_FILL_EXTENDED_BAND_FRAC = 0.12,  -- extended band = 12% of gap width
	ARCTIC_FILL_TILE_PCT = 42,
	ARCTIC_FILL_TILE_PCT_ROW_VAR = 18,
	ARCTIC_FILL_TILE_PCT_NEAR_EDGE = 78,  -- first 3 rows: much higher fill (78% vs 42%)
	ARCTIC_FILL_HILLS_PCT = 45,
	ARCTIC_FILL_HILLS_ROW_VAR = 20,
	ARCTIC_RIDGE_PCT = 35,  -- % of maps: strong mountain ridge along polar land, protruding to water edge
	ARCTIC_RIDGE_WIDTH_MIN = 3, ARCTIC_RIDGE_WIDTH_MAX = 6,  -- ridge width in columns

	-- Phase 3: Ocean gaps (water cuts through arms)
	GAP_POLICY = "always",
	GAP_OPTIONAL_PCT = 60,
	GAP_COUNT_MIN = 1, GAP_COUNT_MAX = 3,  -- fewer gaps = more cohesive arms
	GAP_THICKNESS_MIN = 1, GAP_THICKNESS_MAX = 4,  -- min width when not cutting full; unused if GAP_CUT_FULL_WIDTH
	GAP_CUT_FULL_WIDTH = true,
	GAP_SPLINTER_PCT = 100,  -- all gaps zigzag (splintered path), no straight cuts
	GAP_SPLINTER_STEP_PCT = 35,  -- per step: % chance to move row up/down (zigzag)
	GAP_DIST_FROM_EDGE_MIN = 6, GAP_DIST_FROM_EDGE_MAX = 12,

	-- Extended inland variant (10%): land extends further toward pangaea, sparse (mountains/lakes), guaranteed vertical sea passage
	EXTENDED_INLAND_PCT = 50,  -- testing; change back to 10 when done
	EXTENDED_INLAND_DEPTH_BONUS_MIN = 4, EXTENDED_INLAND_DEPTH_BONUS_MAX = 8,
	EXTENDED_INLAND_WIDTH_MAX = 12,
	EXTENDED_INLAND_TILE_PCT = 42,
	EXTENDED_INLAND_MTN_PCT = 25, EXTENDED_INLAND_LAKE_PCT = 30,
};

local function isLand(plotTypes, x, y, iW, iH)
	if x < 0 or x >= iW or y < 0 or y >= iH then return false; end
	local t = plotTypes[y * iW + x];
	return t == PlotTypes.PLOT_LAND or t == PlotTypes.PLOT_HILLS or t == PlotTypes.PLOT_MOUNTAIN;
end

------------------------------------------------------------------------------
-- PANGAEA EMBRACE
------------------------------------------------------------------------------
local function findPangeaExtentAtEdge(plotTypes, iW, iH, southEdge, scanDepth)
	local extent = { west = iW, east = -1, maxDistFromEdge = 0 };
	local edgeY = southEdge and 0 or (iH - 1);
	for x = 0, iW - 1 do
		for d = 0, scanDepth do
			local y = southEdge and d or (edgeY - d);
			if y >= 0 and y < iH and isLand(plotTypes, x, y, iW, iH) then
				if x < extent.west then extent.west = x; end
				if x > extent.east then extent.east = x; end
				if d > extent.maxDistFromEdge then extent.maxDistFromEdge = d; end
				break;
			end
		end
	end
	return extent;
end

local function drawPangaeaEmbrace(plotTypes, iW, iH, wrapX, wrapY)
	-- wrapY maps are not supported (arms need clear N and S edges).
	if wrapY then return false; end

	-- Pick whether the arms grow from the south edge (y=0) or north edge (y=iH-1).
	-- The pangea body sits on the opposite side of the map.
	local southEdge = (Map.Rand(2, "") == 0);
	local edgeY = southEdge and 0 or (iH - 1);

	-- Scan inward from the chosen edge (up to 25 rows) to locate the pangea.
	-- Returns: extent.west/east = leftmost/rightmost pangea column found near the edge.
	--          extent.maxDistFromEdge = how many rows in from the edge the pangea starts.
	local extent = findPangeaExtentAtEdge(plotTypes, iW, iH, southEdge, 25);

	-- Need the pangea to span at least 15 columns near the edge, otherwise there
	-- is no room for two arms with a gap between them.
	local span = extent.east - extent.west;
	if span < 15 then return false; end

	-- Ensure opposite pole has passage: scan from the other edge; reject if land spans full width.
	--[[ testing: commented out
	local extentOpp = findPangeaExtentAtEdge(plotTypes, iW, iH, not southEdge, 8);
	if extentOpp.east >= extentOpp.west and (extentOpp.east - extentOpp.west) >= iW - 1 then return false; end
	--]]

	-- Arm count: 1, 2, or 3 (weighted by ARM_COUNT_ODDS)
	local armCount;
	do
		local total = 0;
		for n, w in pairs(CONFIG.ARM_COUNT_ODDS) do total = total + w; end
		local roll = Map.Rand(total, "");
		local acc = 0;
		for n = 1, 3 do
			local w = CONFIG.ARM_COUNT_ODDS[n] or 0;
			acc = acc + w;
			if roll < acc then armCount = n; break; end
		end
		armCount = armCount or 2;
	end

	-- westAnchor/eastAnchor: variable positioning. Inset = move inward from extremes.
	-- Jitter = random shift ±N% of span per anchor.
	local insetPct = CONFIG.ARM_ANCHOR_INSET_MIN + Map.Rand(CONFIG.ARM_ANCHOR_INSET_MAX - CONFIG.ARM_ANCHOR_INSET_MIN + 1, "");
	local jitterPct = CONFIG.ARM_ANCHOR_JITTER_PCT;
	local inset = math.floor(span * insetPct / 100);
	local jitterW = math.floor(span * (Map.Rand(jitterPct * 2 + 1, "") - jitterPct) / 100);
	local jitterE = math.floor(span * (Map.Rand(jitterPct * 2 + 1, "") - jitterPct) / 100);
	local westAnchor = extent.west + inset + jitterW;
	local eastAnchor = extent.east - inset + jitterE;
	westAnchor = math.max(extent.west, math.min(westAnchor, extent.east - 5));
	eastAnchor = math.min(extent.east, math.max(eastAnchor, extent.west + 5));
	if westAnchor >= eastAnchor then return false; end

	local drawWest = (armCount == 1 and Map.Rand(2, "") == 0) or (armCount >= 2);
	local drawEast = (armCount == 1 and not drawWest) or (armCount >= 2);
	local drawCenter = (armCount == 3);

	local armLenW = drawWest and (CONFIG.ARM_WIDTH_MIN + Map.Rand(CONFIG.ARM_WIDTH_RANGE, "")) or 0;
	local armLenE = drawEast and (CONFIG.ARM_WIDTH_MIN + Map.Rand(CONFIG.ARM_WIDTH_RANGE, "")) or 0;
	local armLenC = drawCenter and (CONFIG.ARM_WIDTH_MIN + Map.Rand(CONFIG.ARM_WIDTH_RANGE, "")) or 0;
	local centerAnchor = drawCenter and (westAnchor + math.floor((eastAnchor - westAnchor) / 2)) or westAnchor;

	local seaMinX = drawWest and (westAnchor + armLenW) or westAnchor;
	local seaMaxX = drawEast and (eastAnchor - armLenE) or eastAnchor;
	if drawCenter then
		seaMinX = math.min(seaMinX, centerAnchor - math.floor(armLenC / 2));
		seaMaxX = math.max(seaMaxX, centerAnchor + math.floor(armLenC / 2));
	end
	local gap = seaMaxX - seaMinX;
	if gap < 0 then return false; end
	local mergeAtEdge = (armCount == 2 and gap <= CONFIG.MERGE_GAP_THRESHOLD and Map.Rand(100, "") < CONFIG.MERGE_PCT);

	local extendedInland = (Map.Rand(100, "") < (CONFIG.EXTENDED_INLAND_PCT or 0));
	local traversibleCol = nil;
	if extendedInland and gap >= 2 then
		traversibleCol = seaMinX + Map.Rand(math.max(1, gap + 1), "");
		if wrapX then traversibleCol = ((traversibleCol % iW) + iW) % iW; end
	end

	-- armDepth: target N-S length of each arm, just enough to bridge the gap
	-- from the map edge to where the pangea was detected (+1 to ensure contact).
	-- Extended variant: extend up to 12 rows toward pangaea.
	local armDepth = extent.maxDistFromEdge + 1;
	if extendedInland then
		local bonus = CONFIG.EXTENDED_INLAND_DEPTH_BONUS_MIN + Map.Rand(CONFIG.EXTENDED_INLAND_DEPTH_BONUS_MAX - CONFIG.EXTENDED_INLAND_DEPTH_BONUS_MIN + 1, "");
		armDepth = math.min(CONFIG.EXTENDED_INLAND_WIDTH_MAX or 12, armDepth + bonus);
	end
	local armWidthW = drawWest and math.max(3, armDepth + Map.Rand(3, "")) or 0;
	local armWidthE = drawEast and math.max(3, armDepth + Map.Rand(3, "")) or 0;
	local armWidthC = drawCenter and math.max(3, armDepth + Map.Rand(3, "")) or 0;

	-- -------------------------------------------------------------------------
	-- PHASE 1: Paint arm land tiles.
	-- Spec: "Width: 1-8 tiles, varies gradually along length. Generally thickens
	-- toward map edge (not always)." We iterate depth (d) first; at each row,
	-- widthAtD = E-W extent, thickens from 1-2 at pangea to armLen at edge.
	-- -------------------------------------------------------------------------
	local curveAmp  = (Map.Rand(100, "") < CONFIG.SOFTER_CURVE_PCT) and (2.0 + Map.Rand(2, "") * 0.25) or (3.0 + Map.Rand(3, ""));
	local curveFreq = (Map.Rand(100, "") < CONFIG.GENTLER_FREQ_PCT) and (0.30 + Map.Rand(2, "") * 0.05) or (0.50 + Map.Rand(4, "") * 0.09);
	local thickenBias = (Map.Rand(100, "") < CONFIG.THICKEN_TOWARD_EDGE_PCT) and 1 or 0;
	local edgeExpand = (Map.Rand(100, "") < CONFIG.EDGE_EXPAND_PCT);
	local v = CONFIG.CURVE_AMP_VARIATION_PCT / 100;
	local curveAmpW = curveAmp * (1 - v + Map.Rand(math.floor(v * 200) + 1, "") / 100);
	local curveAmpE = curveAmp * (1 - v + Map.Rand(math.floor(v * 200) + 1, "") / 100);
	local curveAmpC = drawCenter and (curveAmp * (1 - v + Map.Rand(math.floor(v * 200) + 1, "") / 100)) or 0;

	local westTiles = {};
	local eastTiles = {};
	local centerTiles = {};
	local allTilesSet = {};
	local maxDepth = math.max(armDepth, armWidthW or 0, armWidthE or 0, armWidthC or 0);

	local lastW, lastE, lastC = {}, {}, {};
	local function forceChangeIfStraight(last, w, minW, maxW)
		if #last < (CONFIG.ARM_STRAIGHT_FORCE_AT or 5) - 1 then return w; end
		local v = last[#last];
		for i = #last - 1, 1, -1 do if last[i] ~= v then return w; end end
		if w ~= v then return w; end
		local delta = (Map.Rand(2, "straight") == 0) and -1 or 1;
		return math.max(minW, math.min(maxW, w + delta));
	end

	for d = 0, maxDepth - 1 do
		local y = southEdge and d or (edgeY - d);
		if y < 0 or y >= iH then break; end
		local t = (maxDepth > 1) and (d / (maxDepth - 1)) or 1;
		if thickenBias == 0 then t = 1 - t; end
		local widthAtD_W = drawWest and math.max(CONFIG.ARM_WIDTH_AT_PANGEA_MIN, math.floor(CONFIG.ARM_WIDTH_AT_PANGEA_MIN + (armLenW - CONFIG.ARM_WIDTH_AT_PANGEA_MIN) * t) + Map.Rand(2, "") - 1) or 0;
		local widthAtD_E = drawEast and math.max(CONFIG.ARM_WIDTH_AT_PANGEA_MIN, math.floor(CONFIG.ARM_WIDTH_AT_PANGEA_MIN + (armLenE - CONFIG.ARM_WIDTH_AT_PANGEA_MIN) * t) + Map.Rand(2, "") - 1) or 0;
		local widthAtD_C = drawCenter and math.max(CONFIG.ARM_WIDTH_AT_PANGEA_MIN, math.floor(CONFIG.ARM_WIDTH_AT_PANGEA_MIN + (armLenC - CONFIG.ARM_WIDTH_AT_PANGEA_MIN) * t) + Map.Rand(2, "") - 1) or 0;
		if widthAtD_W == 1 and Map.Rand(100, "arm1") >= (CONFIG.ARM_WIDTH_1_TILE_ALLOW_PCT or 5) then widthAtD_W = 2; end
		if widthAtD_E == 1 and Map.Rand(100, "arm1") >= (CONFIG.ARM_WIDTH_1_TILE_ALLOW_PCT or 5) then widthAtD_E = 2; end
		if widthAtD_C == 1 and Map.Rand(100, "arm1") >= (CONFIG.ARM_WIDTH_1_TILE_ALLOW_PCT or 5) then widthAtD_C = 2; end
		if edgeExpand and d >= maxDepth - CONFIG.EDGE_EXPAND_ROWS then
			if drawWest then widthAtD_W = armLenW + 1 + Map.Rand(2, ""); end
			if drawEast then widthAtD_E = armLenE + 1 + Map.Rand(2, ""); end
			if drawCenter then widthAtD_C = armLenC + 1 + Map.Rand(2, ""); end
		end
		widthAtD_W = math.min(armLenW + 3, widthAtD_W);
		widthAtD_E = math.min(armLenE + 3, widthAtD_E);
		widthAtD_C = math.min(armLenC + 3, widthAtD_C);
		if d >= 4 then
			local cap = extendedInland and (CONFIG.EXTENDED_INLAND_WIDTH_MAX or 12) or CONFIG.ARM_WIDTH_MAX_INLAND;
			widthAtD_W = math.min(cap, widthAtD_W);
			widthAtD_E = math.min(cap, widthAtD_E);
			widthAtD_C = math.min(cap, widthAtD_C);
		end
		local cap = (d >= 4) and (extendedInland and (CONFIG.EXTENDED_INLAND_WIDTH_MAX or 12) or CONFIG.ARM_WIDTH_MAX_INLAND) or 99;
		widthAtD_W = drawWest and forceChangeIfStraight(lastW, widthAtD_W, CONFIG.ARM_WIDTH_AT_PANGEA_MIN, math.min(armLenW + 3, cap)) or 0;
		widthAtD_E = drawEast and forceChangeIfStraight(lastE, widthAtD_E, CONFIG.ARM_WIDTH_AT_PANGEA_MIN, math.min(armLenE + 3, cap)) or 0;
		widthAtD_C = drawCenter and forceChangeIfStraight(lastC, widthAtD_C, CONFIG.ARM_WIDTH_AT_PANGEA_MIN, math.min(armLenC + 3, cap)) or 0;
		if drawWest then lastW[#lastW + 1] = widthAtD_W; if #lastW > (CONFIG.ARM_STRAIGHT_FORCE_AT or 5) then table.remove(lastW, 1); end end
		if drawEast then lastE[#lastE + 1] = widthAtD_E; if #lastE > (CONFIG.ARM_STRAIGHT_FORCE_AT or 5) then table.remove(lastE, 1); end end
		if drawCenter then lastC[#lastC + 1] = widthAtD_C; if #lastC > (CONFIG.ARM_STRAIGHT_FORCE_AT or 5) then table.remove(lastC, 1); end end

		if drawWest then
			for w = 0, widthAtD_W - 1 do
				local baseX = westAnchor + w;
				local x = baseX + math.floor(curveAmpW * math.sin(d * curveFreq));
				if wrapX then x = ((x % iW) + iW) % iW; end
				if x < 0 or x >= iW then break; end
				if isLand(plotTypes, x, y, iW, iH) then break; end
				local key = y * iW + x;
				if not allTilesSet[key] then
					westTiles[#westTiles + 1] = {x, y};
					allTilesSet[key] = true;
				end
			end
		end

		if drawEast then
			for w = 0, widthAtD_E - 1 do
				local baseX = eastAnchor - w;
				local x = baseX - math.floor(curveAmpE * math.sin(d * curveFreq));
				if wrapX then x = ((x % iW) + iW) % iW; end
				if x < 0 or x >= iW then break; end
				if isLand(plotTypes, x, y, iW, iH) then break; end
				local key = y * iW + x;
				if not allTilesSet[key] then
					eastTiles[#eastTiles + 1] = {x, y};
					allTilesSet[key] = true;
				end
			end
		end

		if drawCenter then
			local loW = -math.floor(widthAtD_C / 2);
			local hiW = math.floor((widthAtD_C - 1) / 2);
			for w = loW, hiW do
				local baseX = centerAnchor + w;
				local x = baseX + math.floor(curveAmpC * math.sin(d * curveFreq));
				if wrapX then x = ((x % iW) + iW) % iW; end
				if x < 0 or x >= iW then break; end
				if isLand(plotTypes, x, y, iW, iH) then break; end
				local key = y * iW + x;
				if not allTilesSet[key] then
					centerTiles[#centerTiles + 1] = {x, y};
					allTilesSet[key] = true;
				end
			end
		end
	end

	if mergeAtEdge and gap > 0 then
		for d = math.max(0, maxDepth - CONFIG.EDGE_EXPAND_ROWS), maxDepth - 1 do
			local y = southEdge and d or (edgeY - d);
			if y < 0 or y >= iH then break; end
			for gx = seaMinX, seaMaxX do
				local gwx = wrapX and (((gx % iW) + iW) % iW) or gx;
				if gwx >= 0 and gwx < iW and not isLand(plotTypes, gwx, y, iW, iH) then
					local key = y * iW + gwx;
					if not allTilesSet[key] then
						westTiles[#westTiles + 1] = {gwx, y};
						allTilesSet[key] = true;
					end
				end
			end
		end
	end

	-- -------------------------------------------------------------------------
	-- PHASE 2: Terrain. Ridge = mountain (variable position: outer/center/inner).
	-- Thicker arms: ridge is 2 tiles; variable placement per arm.
	-- -------------------------------------------------------------------------
	local westMinX, westMaxX = {}, {};
	local eastMinX, eastMaxX = {}, {};
	local centerMinX, centerMaxX = {}, {};
	for _, t in ipairs(westTiles) do
		local x, y = t[1], t[2];
		if not westMinX[y] or x < westMinX[y] then westMinX[y] = x; end
		if not westMaxX[y] or x > westMaxX[y] then westMaxX[y] = x; end
	end
	for _, t in ipairs(eastTiles) do
		local x, y = t[1], t[2];
		if not eastMinX[y] or x < eastMinX[y] then eastMinX[y] = x; end
		if not eastMaxX[y] or x > eastMaxX[y] then eastMaxX[y] = x; end
	end
	for _, t in ipairs(centerTiles) do
		local x, y = t[1], t[2];
		if not centerMinX[y] or x < centerMinX[y] then centerMinX[y] = x; end
		if not centerMaxX[y] or x > centerMaxX[y] then centerMaxX[y] = x; end
	end
	-- 1-arm: fill opposite boundary from pangea extent for arctic fill
	if not drawEast then
		for y in pairs(westMaxX) do
			for x = westMaxX[y] + 1, extent.east do
				if isLand(plotTypes, x, y, iW, iH) then eastMinX[y] = x; break; end
			end
		end
	end
	if not drawWest then
		for y in pairs(eastMinX) do
			for x = eastMinX[y] - 1, extent.west, -1 do
				if isLand(plotTypes, x, y, iW, iH) then westMaxX[y] = x; break; end
			end
		end
	end

	-- Arctic fill: land between arms near edge (snow later)
	-- maxRow scales with arm depth: longer arms = more polar land protrusion from edge.
	-- Base 4 rows; armDepth 7+ -> 5 rows; armDepth 9+ -> 6 rows. POLAR_EDGE_EXTEND adds extra rows.
	-- 50% (ARCTIC_FILL_8_ROW_PCT): edge protrusion goes up to 8 rows.
	local arcticTiles = {};
	local maxRow = (maxDepth >= 9) and 6 or (maxDepth >= 7) and 5 or 4;
	if Map.Rand(100, "") < (CONFIG.ARCTIC_FILL_8_ROW_PCT or 0) then
		maxRow = math.min(maxDepth, 8);
	else
		maxRow = math.min(maxDepth, maxRow + (CONFIG.ARCTIC_FILL_EDGE_EXTEND_ROWS or 0));
	end
	if extendedInland then maxRow = math.min(maxDepth, 12); end
	local hasExtended = (Map.Rand(100, "") < CONFIG.ARCTIC_FILL_EXTENDED_MAP_PCT);
	local extXLo, extXHi = nil, nil;
	if hasExtended then
		local gapWidth, sampleW, sampleE = 0, nil, nil;
		for ry = 0, 5 do
			local y = southEdge and ry or (iH - 1 - ry);
			if y >= 0 and y < iH then
				local w, e = westMaxX[y], eastMinX[y];
				if w and e and w + 1 < e then
					gapWidth = math.max(gapWidth, e - w - 1);
					sampleW, sampleE = w, e;
				end
			end
		end
		if sampleW and sampleE and gapWidth >= 2 then
			local bandW = math.max(2, math.floor(gapWidth * CONFIG.ARCTIC_FILL_EXTENDED_BAND_FRAC));
			extXLo = sampleW + 1 + Map.Rand(math.max(0, (sampleE - sampleW - 1) - bandW), "");
			extXHi = extXLo + bandW - 1;
			maxRow = 6;
		end
	end
	local depthByX = {};
	local y0 = southEdge and 0 or (iH - 1);
	local y1 = southEdge and math.min(maxRow, iH - 1) or math.max(0, (iH - 1) - maxRow);
	local dy = southEdge and 1 or -1;
	for y = y0, y1, dy do
		local wMax, eMin = westMaxX[y], eastMinX[y];
		if wMax and eMin and wMax + 1 < eMin then
			local distFromEdge = southEdge and y or ((iH - 1) - y);
			local rowPct = (distFromEdge <= 2) and CONFIG.ARCTIC_FILL_TILE_PCT_NEAR_EDGE
				or (CONFIG.ARCTIC_FILL_TILE_PCT + (Map.Rand(CONFIG.ARCTIC_FILL_TILE_PCT_ROW_VAR * 2 + 1, "") - CONFIG.ARCTIC_FILL_TILE_PCT_ROW_VAR));
			local rowHills = CONFIG.ARCTIC_FILL_HILLS_PCT + (Map.Rand(CONFIG.ARCTIC_FILL_HILLS_ROW_VAR * 2 + 1, "") - CONFIG.ARCTIC_FILL_HILLS_ROW_VAR);
			rowHills = math.max(20, math.min(65, rowHills));
			local function tryFill(gx)
				if gx < 0 or gx >= iW or isLand(plotTypes, gx, y, iW, iH) then return; end
				if traversibleCol and gx == traversibleCol then return; end
				local useExtendedFill = extendedInland and distFromEdge >= 7;
				if not useExtendedFill then
					local depth = depthByX[gx];
					if not depth then
						if extXLo and gx >= extXLo and gx <= extXHi then
							depth = 6 + Map.Rand(2, "");
						else
							depth = CONFIG.ARCTIC_FILL_DEPTH_MIN + Map.Rand(CONFIG.ARCTIC_FILL_DEPTH_MAX - CONFIG.ARCTIC_FILL_DEPTH_MIN + 1, "");
						end
						depthByX[gx] = depth;
					end
					if distFromEdge >= depth then return; end
					if distFromEdge > 4 and not (extXLo and gx >= extXLo and gx <= extXHi) then return; end
				end
				local pct = useExtendedFill and (CONFIG.EXTENDED_INLAND_TILE_PCT or 42) or rowPct;
				if Map.Rand(100, "") >= pct then return; end
				local key = y * iW + gx;
				if not allTilesSet[key] then
					allTilesSet[key] = true;
					if useExtendedFill then
						local r = Map.Rand(100, "");
						if r < (CONFIG.EXTENDED_INLAND_MTN_PCT or 25) then
							plotTypes[key] = PlotTypes.PLOT_MOUNTAIN;
							arcticTiles[#arcticTiles + 1] = { gx, y };
						elseif r < (CONFIG.EXTENDED_INLAND_MTN_PCT or 25) + (CONFIG.EXTENDED_INLAND_LAKE_PCT or 30) then
							plotTypes[key] = PlotTypes.PLOT_OCEAN;
						else
							plotTypes[key] = (Map.Rand(100, "") < 55) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND;
							arcticTiles[#arcticTiles + 1] = { gx, y };
						end
					else
						arcticTiles[#arcticTiles + 1] = { gx, y };
						plotTypes[key] = (Map.Rand(100, "") < rowHills) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND;
					end
				end
			end
			if wMax < eMin then
				for x = wMax + 1, eMin - 1 do
					tryFill(wrapX and (((x % iW) + iW) % iW) or x);
				end
			elseif wrapX then
				for x = wMax + 1, iW - 1 do tryFill(x); end
				for x = 0, eMin - 1 do tryFill(x); end
			end
		end
	end

	-- Arctic ridge: strong mountain band along polar land, protruding to water edge
	if #arcticTiles > 0 and Map.Rand(100, "") < CONFIG.ARCTIC_RIDGE_PCT then
		local xLo, xHi = iW, 0;
		for _, t in ipairs(arcticTiles) do
			local gx = t[1];
			if gx < xLo then xLo = gx; end
			if gx > xHi then xHi = gx; end
		end
		local span = xHi - xLo + 1;
		local ridgeW = CONFIG.ARCTIC_RIDGE_WIDTH_MIN + Map.Rand(CONFIG.ARCTIC_RIDGE_WIDTH_MAX - CONFIG.ARCTIC_RIDGE_WIDTH_MIN + 1, "");
		ridgeW = math.min(ridgeW, span);
		if ridgeW >= 1 then
			local offset = (span > ridgeW) and Map.Rand(span - ridgeW + 1, "") or 0;
			local ridgeXLo = xLo + offset;
			local ridgeXHi = ridgeXLo + ridgeW - 1;
			for _, t in ipairs(arcticTiles) do
				local gx, gy = t[1], t[2];
				if gx >= ridgeXLo and gx <= ridgeXHi then
					plotTypes[gy * iW + gx] = PlotTypes.PLOT_MOUNTAIN;
				end
			end
		end
	end

	local ridgePosW = Map.Rand(CONFIG.RIDGE_POSITIONS, "");
	local ridgePosE = Map.Rand(CONFIG.RIDGE_POSITIONS, "");
	local ridgePosC = drawCenter and Map.Rand(CONFIG.RIDGE_POSITIONS, "") or 0;
	local splinteredRidge = (Map.Rand(100, "") < (CONFIG.SPLINTERED_RIDGE_PCT or 0));

	local function getRidgeWidth(w)
		local base = 2 + Map.Rand(2, "");
		local widthBias = (w >= 6 and Map.Rand(100, "") < 35) and 1 or 0;
		if w >= 8 and Map.Rand(100, "") < 18 then widthBias = widthBias + 1; end
		return math.min(w, base + widthBias);
	end

	local function buildRidgeWidthByRow(minXByY, maxXByY, useSplintered)
		local rwByY = {};
		local rowList = {};
		for y in pairs(minXByY) do
			if maxXByY[y] then
				rowList[#rowList + 1] = y;
			end
		end
		table.sort(rowList);
		local splinteredW = useSplintered and (CONFIG.SPLINTERED_RIDGE_WIDTH_MIN + Map.Rand(CONFIG.SPLINTERED_RIDGE_WIDTH_MAX - CONFIG.SPLINTERED_RIDGE_WIDTH_MIN + 1, "")) or nil;
		for _, y in ipairs(rowList) do
			local w = maxXByY[y] - minXByY[y] + 1;
			rwByY[y] = math.min(w, splinteredW or getRidgeWidth(w));
		end
		local thinCount = 0;
		for _, y in ipairs(rowList) do
			if rwByY[y] == 1 then
				thinCount = thinCount + 1;
				local w = maxXByY[y] - minXByY[y] + 1;
				if thinCount >= (CONFIG.RIDGE_THIN_FORCE_AT or 999) then
					rwByY[y] = math.min(w, 2);
					thinCount = 0;
				elseif thinCount >= CONFIG.RIDGE_THIN_EXPAND_ROWS and Map.Rand(100, "") < CONFIG.RIDGE_THIN_EXPAND_PCT then
					rwByY[y] = math.min(w, 2);
					thinCount = 0;
				end
			else
				thinCount = 0;
			end
		end
		return rwByY;
	end

	local ridgeWidthWest = buildRidgeWidthByRow(westMinX, westMaxX, splinteredRidge);
	local ridgeWidthEast = buildRidgeWidthByRow(eastMinX, eastMaxX, splinteredRidge);
	local ridgeWidthCenter = drawCenter and buildRidgeWidthByRow(centerMinX, centerMaxX, splinteredRidge) or {};

	local function isRidgeWest(x, y)
		local lo, hi = westMinX[y], westMaxX[y];
		if not lo then return false; end
		hi = hi or lo;
		local w = hi - lo + 1;
		local ridgeW = math.min(ridgeWidthWest[y] or 1, w);
		local start = (ridgePosW == 0) and lo or (ridgePosW == 1) and (lo + math.floor((w - ridgeW) / 2)) or (hi - ridgeW + 1);
		return x >= start and x < start + ridgeW;
	end
	local function isRidgeEast(x, y)
		local lo, hi = eastMinX[y], eastMaxX[y];
		if not hi then return false; end
		lo = lo or hi;
		local w = hi - lo + 1;
		local ridgeW = math.min(ridgeWidthEast[y] or 1, w);
		local start = (ridgePosE == 0) and (hi - ridgeW + 1) or (ridgePosE == 1) and (lo + math.floor((w - ridgeW) / 2)) or lo;
		return x >= start and x < start + ridgeW;
	end
	local function isRidgeCenter(x, y)
		if not drawCenter then return false; end
		local lo, hi = centerMinX[y], centerMaxX[y];
		if not lo then return false; end
		hi = hi or lo;
		local w = hi - lo + 1;
		local ridgeW = math.min(ridgeWidthCenter[y] or 1, w);
		local start = (ridgePosC == 0) and lo or (ridgePosC == 1) and (lo + math.floor((w - ridgeW) / 2)) or (hi - ridgeW + 1);
		return x >= start and x < start + ridgeW;
	end

	local ridgeSet = {};
	for _, t in ipairs(westTiles) do
		if isRidgeWest(t[1], t[2]) then ridgeSet[t[1] .. "," .. t[2]] = true; end
	end
	for _, t in ipairs(eastTiles) do
		if isRidgeEast(t[1], t[2]) then ridgeSet[t[1] .. "," .. t[2]] = true; end
	end
	for _, t in ipairs(centerTiles) do
		if isRidgeCenter(t[1], t[2]) then ridgeSet[t[1] .. "," .. t[2]] = true; end
	end

	local heavyRidge = (Map.Rand(100, "") < CONFIG.HEAVY_RIDGE_PCT);
	local riftCountMin = heavyRidge and CONFIG.HEAVY_RIDGE_RIFT_COUNT_MIN or CONFIG.RIDGE_RIFT_COUNT_MIN;
	local riftCountMax = heavyRidge and CONFIG.HEAVY_RIDGE_RIFT_COUNT_MAX or CONFIG.RIDGE_RIFT_COUNT_MAX;
	local riftHeightMin = heavyRidge and CONFIG.HEAVY_RIDGE_RIFT_HEIGHT or CONFIG.RIDGE_RIFT_HEIGHT_MIN;
	local riftHeightMax = heavyRidge and CONFIG.HEAVY_RIDGE_RIFT_HEIGHT or CONFIG.RIDGE_RIFT_HEIGHT_MAX;

	local function buildRiftRows(tiles)
		local rows = {};
		for _, t in ipairs(tiles) do rows[t[2]] = true; end
		local rowList = {};
		for y in pairs(rows) do rowList[#rowList + 1] = y; end
		table.sort(rowList);
		if #rowList < 2 then return {}, {}; end
		local riftRowSet = {};
		local riftClusterBands = {};
		local nSec = CONFIG.RIDGE_SECTION_COUNT;
		local secSize = math.max(1, math.floor(#rowList / nSec));
		local secWeights = {};
		for s = 1, nSec do
			secWeights[s] = 0.5 + Map.Rand(11, "") / 10;
		end
		local totalWeight = 0;
		for s = 1, nSec do totalWeight = totalWeight + secWeights[s]; end
		local numRifts = riftCountMin + Map.Rand(riftCountMax - riftCountMin + 1, "");
		numRifts = math.min(numRifts, math.max(1, #rowList - 1));
		local clusterCenter;
		if heavyRidge and #rowList >= 3 then
			clusterCenter = rowList[1 + Map.Rand(#rowList, "")];
		end
		local bandRows = CONFIG.RIDGE_RIFT_CLUSTER_BAND_ROWS;
		for _ = 1, numRifts do
			local y;
			if clusterCenter then
				local offset = Map.Rand(5, "") - 2;
				y = clusterCenter + offset;
				y = math.max(rowList[1], math.min(rowList[#rowList], y));
			else
				local r = Map.Rand(math.floor(totalWeight * 100), "") / 100;
				local acc = 0;
				local sec = 1;
				for s = 1, nSec do
					acc = acc + secWeights[s];
					if r < acc then sec = s; break; end
				end
				local loIdx = 1 + (sec - 1) * secSize;
				local hiIdx = (sec < nSec) and (sec * secSize) or #rowList;
				local pickIdx = loIdx + Map.Rand(math.max(1, hiIdx - loIdx + 1), "") - 1;
				y = rowList[math.min(pickIdx, #rowList)];
			end
			y = math.max(rowList[1], math.min(rowList[#rowList], y));
			if Map.Rand(100, "") < CONFIG.RIDGE_RIFT_CLUSTER_PCT and (rowList[#rowList] - rowList[1] + 1) >= bandRows then
				local yMin = math.max(rowList[1], y);
				local yMax = math.min(rowList[#rowList], yMin + bandRows - 1);
				if yMax - yMin + 1 >= 3 then
					riftClusterBands[#riftClusterBands + 1] = { yMin = yMin, yMax = yMax };
				else
					riftRowSet[y] = true;
				end
			else
				local h = riftHeightMin + Map.Rand(riftHeightMax - riftHeightMin + 1, "");
				for dy = 0, h - 1 do
					riftRowSet[y + dy] = true;
				end
			end
		end
		return riftRowSet, riftClusterBands;
	end

	local function isInClusterBand(y, bands)
		for _, b in ipairs(bands) do
			if y >= b.yMin and y <= b.yMax then return true; end
		end
		return false;
	end

	local function buildRiftTileSet(tiles, riftClusterBands, isRidge)
		local riftTileSet = {};
		for _, band in ipairs(riftClusterBands) do
			local ridgeTiles = {};
			for _, t in ipairs(tiles) do
				if t[2] >= band.yMin and t[2] <= band.yMax and isRidge(t[1], t[2]) then
					ridgeTiles[#ridgeTiles + 1] = { t[1], t[2] };
				end
			end
			if #ridgeTiles >= 2 then
				local numPaths = CONFIG.RIDGE_RIFT_CLUSTER_NUM_PATHS;
				local pathTilesMin = CONFIG.RIDGE_RIFT_CLUSTER_PATH_TILES_MIN;
				local pathTilesMax = CONFIG.RIDGE_RIFT_CLUSTER_PATH_TILES_MAX;
				local used = {};
				for p = 1, numPaths do
					local n = pathTilesMin + Map.Rand(pathTilesMax - pathTilesMin + 1, "");
					local candidates = {};
					for i = 1, #ridgeTiles do
						local k = ridgeTiles[i][1] .. "," .. ridgeTiles[i][2];
						if not used[k] then candidates[#candidates + 1] = ridgeTiles[i]; end
					end
					if #candidates == 0 then break; end
					local idx = 1 + Map.Rand(#candidates, "");
					local seed = candidates[idx];
					riftTileSet[seed[1] .. "," .. seed[2]] = true;
					used[seed[1] .. "," .. seed[2]] = true;
					for _ = 2, n do
						local neighbors = {};
						for dir = 1, 6 do
							local nx, ny = GetHexNeighbor(seed[1], seed[2], dir, iW, iH, wrapX, wrapY);
							if nx >= 0 and nx < iW and ny >= 0 and ny < iH then
								local nk = nx .. "," .. ny;
								if not used[nk] then
									for _, rt in ipairs(ridgeTiles) do
										if rt[1] == nx and rt[2] == ny then
											neighbors[#neighbors + 1] = { nx, ny };
											break;
										end
									end
								end
							end
						end
						if #neighbors == 0 then break; end
						local nb = neighbors[1 + Map.Rand(#neighbors, "")];
						riftTileSet[nb[1] .. "," .. nb[2]] = true;
						used[nb[1] .. "," .. nb[2]] = true;
						seed = nb;
					end
				end
			end
		end
		return riftTileSet;
	end

	local westRiftRows, westRiftClusterBands;
	local eastRiftRows, eastRiftClusterBands;
	local centerRiftRows, centerRiftClusterBands;
	if splinteredRidge then
		westRiftRows, westRiftClusterBands = {}, {};
		eastRiftRows, eastRiftClusterBands = {}, {};
		centerRiftRows, centerRiftClusterBands = {}, {};
	else
		westRiftRows, westRiftClusterBands = buildRiftRows(westTiles);
		eastRiftRows, eastRiftClusterBands = buildRiftRows(eastTiles);
		centerRiftRows, centerRiftClusterBands = drawCenter and buildRiftRows(centerTiles) or {}, {};
	end

	local function buildSplinteredGapTileSet(tiles, isRidge)
		local ridgeTiles = {};
		for _, t in ipairs(tiles) do
			if isRidge(t[1], t[2]) then ridgeTiles[#ridgeTiles + 1] = {t[1], t[2]}; end
		end
		if #ridgeTiles < 2 then return {}; end
		local gapMin = CONFIG.SPLINTERED_GAP_COUNT_MIN or 6;
		local gapMax = CONFIG.SPLINTERED_GAP_COUNT_MAX or 14;
		local numGaps = gapMin + Map.Rand(math.max(1, gapMax - gapMin + 1), "splinter");
		numGaps = math.min(numGaps, math.max(1, #ridgeTiles - 1));
		local riftTileSet = {};
		local used = {};
		for _ = 1, numGaps do
			local idx = 1 + Map.Rand(#ridgeTiles, "splinter");
			local t = ridgeTiles[idx];
			if not t then break; end
			local key = t[1] .. "," .. t[2];
			if not used[key] then
				riftTileSet[key] = true;
				used[key] = true;
				if Map.Rand(100, "") < CONFIG.SPLINTERED_GAP_2_TILE_PCT then
					for dir = 1, 6 do
						local nx, ny = GetHexNeighbor(t[1], t[2], dir, iW, iH, wrapX, wrapY);
						if nx >= 0 and nx < iW and ny >= 0 and ny < iH then
							local nk = nx .. "," .. ny;
							if not used[nk] then
								for _, rt in ipairs(ridgeTiles) do
									if rt[1] == nx and rt[2] == ny then
										riftTileSet[nk] = true;
										used[nk] = true;
										break;
									end
								end
								break;
							end
						end
					end
				end
			end
		end
		return riftTileSet;
	end

	local westRiftTileSet = splinteredRidge and buildSplinteredGapTileSet(westTiles, isRidgeWest) or buildRiftTileSet(westTiles, westRiftClusterBands, isRidgeWest);
	local eastRiftTileSet = splinteredRidge and buildSplinteredGapTileSet(eastTiles, isRidgeEast) or buildRiftTileSet(eastTiles, eastRiftClusterBands, isRidgeEast);
	local centerRiftTileSet = splinteredRidge and (drawCenter and buildSplinteredGapTileSet(centerTiles, isRidgeCenter) or {}) or (drawCenter and buildRiftTileSet(centerTiles, centerRiftClusterBands, isRidgeCenter) or {});

	for _, t in ipairs(westTiles) do
		local idx = t[2] * iW + t[1];
		if isRidgeWest(t[1], t[2]) then
			local key = t[1] .. "," .. t[2];
			if westRiftTileSet[key] then
				plotTypes[idx] = CONFIG.RIDGE_RIFT_IS_WATER and PlotTypes.PLOT_OCEAN
					or ((Map.Rand(100, "") < CONFIG.RIDGE_RIFT_HILLS_PCT) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND);
			elseif westRiftRows[t[2]] then
				plotTypes[idx] = CONFIG.RIDGE_RIFT_IS_WATER and PlotTypes.PLOT_OCEAN
					or ((Map.Rand(100, "") < CONFIG.RIDGE_RIFT_HILLS_PCT) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND);
			elseif isInClusterBand(t[2], westRiftClusterBands) then
				plotTypes[idx] = (Map.Rand(100, "") < CONFIG.RIDGE_RIFT_HILLS_PCT) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_MOUNTAIN;
			else
				plotTypes[idx] = PlotTypes.PLOT_MOUNTAIN;
			end
		end
	end
	for _, t in ipairs(eastTiles) do
		local idx = t[2] * iW + t[1];
		if isRidgeEast(t[1], t[2]) then
			local key = t[1] .. "," .. t[2];
			if eastRiftTileSet[key] then
				plotTypes[idx] = CONFIG.RIDGE_RIFT_IS_WATER and PlotTypes.PLOT_OCEAN
					or ((Map.Rand(100, "") < CONFIG.RIDGE_RIFT_HILLS_PCT) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND);
			elseif eastRiftRows[t[2]] then
				plotTypes[idx] = CONFIG.RIDGE_RIFT_IS_WATER and PlotTypes.PLOT_OCEAN
					or ((Map.Rand(100, "") < CONFIG.RIDGE_RIFT_HILLS_PCT) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND);
			elseif isInClusterBand(t[2], eastRiftClusterBands) then
				plotTypes[idx] = (Map.Rand(100, "") < CONFIG.RIDGE_RIFT_HILLS_PCT) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_MOUNTAIN;
			else
				plotTypes[idx] = PlotTypes.PLOT_MOUNTAIN;
			end
		end
	end
	for _, t in ipairs(centerTiles) do
		local idx = t[2] * iW + t[1];
		if isRidgeCenter(t[1], t[2]) then
			local key = t[1] .. "," .. t[2];
			if centerRiftTileSet[key] then
				plotTypes[idx] = CONFIG.RIDGE_RIFT_IS_WATER and PlotTypes.PLOT_OCEAN
					or ((Map.Rand(100, "") < CONFIG.RIDGE_RIFT_HILLS_PCT) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND);
			elseif centerRiftRows[t[2]] then
				plotTypes[idx] = CONFIG.RIDGE_RIFT_IS_WATER and PlotTypes.PLOT_OCEAN
					or ((Map.Rand(100, "") < CONFIG.RIDGE_RIFT_HILLS_PCT) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND);
			elseif isInClusterBand(t[2], centerRiftClusterBands) then
				plotTypes[idx] = (Map.Rand(100, "") < CONFIG.RIDGE_RIFT_HILLS_PCT) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_MOUNTAIN;
			else
				plotTypes[idx] = PlotTypes.PLOT_MOUNTAIN;
			end
		end
	end

	local distToRidge = {};
	local queue = {};
	for k in pairs(ridgeSet) do
		local x, y = k:match("([^,]+),([^,]+)");
		x, y = tonumber(x), tonumber(y);
		distToRidge[k] = 0;
		queue[#queue + 1] = {x, y};
	end
	local q = 1;
	while q <= #queue do
		local x, y = queue[q][1], queue[q][2];
		local key = x .. "," .. y;
		local d = distToRidge[key] or 0;
		for dir = 1, 6 do
			local nx, ny = GetHexNeighbor(x, y, dir, iW, iH, wrapX, wrapY);
			if nx >= 0 and nx < iW and ny >= 0 and ny < iH and allTilesSet[ny * iW + nx] then
				local nk = nx .. "," .. ny;
				if distToRidge[nk] == nil then
					distToRidge[nk] = d + 1;
					queue[#queue + 1] = {nx, ny};
				end
			end
		end
		q = q + 1;
	end

	local function isCoastal(x, y)
		for dir = 1, 6 do
			local nx, ny = GetHexNeighbor(x, y, dir, iW, iH, wrapX, wrapY);
			if nx >= 0 and nx < iW and ny >= 0 and ny < iH then
				if not allTilesSet[ny * iW + nx] and plotTypes[ny * iW + nx] == PlotTypes.PLOT_OCEAN then
					return true;
				end
			end
		end
		return false;
	end

	for _, t in ipairs(westTiles) do
		local idx = t[2] * iW + t[1];
		if not isRidgeWest(t[1], t[2]) then
			local hillsPct = CONFIG.HILLS_PCT_3RD;
			local coastal = isCoastal(t[1], t[2]);
			if coastal then
				local w = westMinX[t[2]] and (westMaxX[t[2]] - westMinX[t[2]] + 1) or 0;
				if w >= CONFIG.COASTAL_THIN_WIDTH then
					hillsPct = 100 - CONFIG.COASTAL_FLAT_PCT;
				else
					hillsPct = math.max(CONFIG.HILLS_PCT_MIN, CONFIG.THIN_STRIP_HILLS_PCT);
				end
			else
				local d = distToRidge[t[1] .. "," .. t[2]];
				if d == 1 then hillsPct = CONFIG.HILLS_PCT_ADJ;
				elseif d == 2 then hillsPct = CONFIG.HILLS_PCT_2ND; end
				hillsPct = math.max(CONFIG.HILLS_PCT_MIN, hillsPct);
			end
			plotTypes[idx] = (Map.Rand(100, "") < hillsPct) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND;
		end
	end
	for _, t in ipairs(eastTiles) do
		local idx = t[2] * iW + t[1];
		if not isRidgeEast(t[1], t[2]) then
			local hillsPct = CONFIG.HILLS_PCT_3RD;
			local coastal = isCoastal(t[1], t[2]);
			if coastal then
				local w = eastMinX[t[2]] and (eastMaxX[t[2]] - eastMinX[t[2]] + 1) or 0;
				if w >= CONFIG.COASTAL_THIN_WIDTH then
					hillsPct = 100 - CONFIG.COASTAL_FLAT_PCT;
				else
					hillsPct = math.max(CONFIG.HILLS_PCT_MIN, CONFIG.THIN_STRIP_HILLS_PCT);
				end
			else
				local d = distToRidge[t[1] .. "," .. t[2]];
				if d == 1 then hillsPct = CONFIG.HILLS_PCT_ADJ;
				elseif d == 2 then hillsPct = CONFIG.HILLS_PCT_2ND; end
				hillsPct = math.max(CONFIG.HILLS_PCT_MIN, hillsPct);
			end
			plotTypes[idx] = (Map.Rand(100, "") < hillsPct) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND;
		end
	end
	for _, t in ipairs(centerTiles) do
		local idx = t[2] * iW + t[1];
		if not isRidgeCenter(t[1], t[2]) then
			local hillsPct = CONFIG.HILLS_PCT_3RD;
			local coastal = isCoastal(t[1], t[2]);
			if coastal then
				local w = centerMinX[t[2]] and (centerMaxX[t[2]] - centerMinX[t[2]] + 1) or 0;
				if w >= CONFIG.COASTAL_THIN_WIDTH then
					hillsPct = 100 - CONFIG.COASTAL_FLAT_PCT;
				else
					hillsPct = math.max(CONFIG.HILLS_PCT_MIN, CONFIG.THIN_STRIP_HILLS_PCT);
				end
			else
				local d = distToRidge[t[1] .. "," .. t[2]];
				if d == 1 then hillsPct = CONFIG.HILLS_PCT_ADJ;
				elseif d == 2 then hillsPct = CONFIG.HILLS_PCT_2ND; end
				hillsPct = math.max(CONFIG.HILLS_PCT_MIN, hillsPct);
			end
			plotTypes[idx] = (Map.Rand(100, "") < hillsPct) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND;
		end
	end

	-- -------------------------------------------------------------------------
	-- PHASE 3: Ocean gaps. Cut water through arms so inner sea connects to outer ocean.
	-- Policy: "always" = guaranteed, "optional" = random chance, "never" = solid arms.
	-- -------------------------------------------------------------------------
	local doGaps = (CONFIG.GAP_POLICY == "always") or
		(CONFIG.GAP_POLICY == "optional" and Map.Rand(100, "") < CONFIG.GAP_OPTIONAL_PCT);
	local numGaps = doGaps and (CONFIG.GAP_COUNT_MIN + Map.Rand(CONFIG.GAP_COUNT_MAX - CONFIG.GAP_COUNT_MIN + 1, "")) or 0;
	local distFromEdge = CONFIG.GAP_DIST_FROM_EDGE_MIN + Map.Rand(CONFIG.GAP_DIST_FROM_EDGE_MAX - CONFIG.GAP_DIST_FROM_EDGE_MIN + 1, "");
	distFromEdge = math.min(distFromEdge, math.max(0, maxDepth - 7));  -- keep >5 from edge, fit in arm

	local function cutSplinteredPath(minXByY, maxXByY, y0, stepDir)
		local lo, hi = minXByY[y0], maxXByY[y0];
		if not lo or not hi then return; end
		local x0 = stepDir > 0 and lo or hi;
		local xEnd = stepDir > 0 and hi or lo;
		local py = y0;
		for x = x0, xEnd, stepDir do
			if minXByY[py] and x >= minXByY[py] and x <= maxXByY[py] then
				local wx = wrapX and (((x % iW) + iW) % iW) or x;
				if wx >= 0 and wx < iW then
					plotTypes[py * iW + wx] = PlotTypes.PLOT_OCEAN;
				end
			end
			if Map.Rand(100, "") < CONFIG.GAP_SPLINTER_STEP_PCT then
				local ny = py + (Map.Rand(2, "") == 0 and 1 or -1);
				if minXByY[ny] and maxXByY[ny] and x >= minXByY[ny] and x <= maxXByY[ny] then
					py = ny;
				end
			end
		end
	end

	local function cutStraightRow(minXByY, maxXByY, y0)
		local lo, hi = minXByY[y0], maxXByY[y0];
		if lo and hi then
			for x = lo, hi do
				local wx = wrapX and (((x % iW) + iW) % iW) or x;
				if wx >= 0 and wx < iW then
					plotTypes[y0 * iW + wx] = PlotTypes.PLOT_OCEAN;
				end
			end
		end
	end

	for g = 1, numGaps do
		local d = southEdge and (maxDepth - 1 - distFromEdge - Map.Rand(2, "")) or (distFromEdge + Map.Rand(2, ""));
		d = math.max(0, math.min(maxDepth - 1, d));
		local y = southEdge and d or (edgeY - d);
		if y >= 0 and y < iH then
			local splinter = Map.Rand(100, "") < CONFIG.GAP_SPLINTER_PCT;
			if splinter then
				if drawWest then cutSplinteredPath(westMinX, westMaxX, y, 1); end
				if drawEast then cutSplinteredPath(eastMinX, eastMaxX, y, -1); end
				if drawCenter then cutSplinteredPath(centerMinX, centerMaxX, y, 1); end
			else
				if drawWest then cutStraightRow(westMinX, westMaxX, y); end
				if drawEast then cutStraightRow(eastMinX, eastMaxX, y); end
				if drawCenter then cutStraightRow(centerMinX, centerMaxX, y); end
			end
		end
	end

	-- Spec: "Entire landmass generated by this script: Ineligible for player starting positions"
	_polar_pangea_excluded_plots = _polar_pangea_excluded_plots or {};
	for idx in pairs(allTilesSet) do
		local pt = plotTypes[idx];
		if pt == PlotTypes.PLOT_LAND or pt == PlotTypes.PLOT_HILLS or pt == PlotTypes.PLOT_MOUNTAIN then
			_polar_pangea_excluded_plots[idx + 1] = true;
		end
	end

	return true;
end

--[==[
------------------------------------------------------------------------------
-- ARCTIC MERGE (disabled)
------------------------------------------------------------------------------
local HILLS_ADJ = 75;
local TUNDRA_LAT = 0.85;

local function isWater(plotTypes, x, y, iW, iH)
	if x < 0 or x >= iW or y < 0 or y >= iH then return false; end
	return plotTypes[y * iW + x] == PlotTypes.PLOT_OCEAN;
end

local function getTundraLatitudeY(iH, southEdge)
	local offset = math.floor((iH / 2) * (1 - TUNDRA_LAT));
	if southEdge then return offset; end
	return iH - 1 - offset;
end

local function rippleToLand(plotTypes, startX, startY, iW, iH, wrapX, southEdge)
	local visited = {};
	local queue = {{startX, startY}};
	visited[startX .. "," .. startY] = true;
	local dist = 0;
	local maxDist = 15;
	while #queue > 0 and dist < maxDist do
		local next = {};
		for _, p in ipairs(queue) do
			local x, y = p[1], p[2];
			if isLand(plotTypes, x, y, iW, iH) then return dist, x, y; end
			for dir = 1, 6 do
				local nx, ny = GetHexNeighbor(x, y, dir, iW, iH, wrapX, false);
				if ny >= 0 and ny < iH then
					local inward = southEdge and (ny > y) or (ny < y);
					if inward then
						local key = nx .. "," .. ny;
						if not visited[key] then
							visited[key] = true;
							next[#next + 1] = {nx, ny};
						end
					end
				end
			end
		end
		queue = next;
		dist = dist + 1;
	end
	return nil, nil, nil;
end

local function findValidXForPangea(plotTypes, iW, iH, southEdge, maxScan)
	local validX = {};
	local edgeY = southEdge and 0 or (iH - 1);
	for x = 0, iW - 1 do
		for d = 1, math.min(maxScan, 12) do
			local y = southEdge and d or (edgeY - d);
			if y >= 0 and y < iH and isLand(plotTypes, x, y, iW, iH) then
				validX[#validX + 1] = x;
				break;
			end
		end
	end
	return validX;
end

local function drawArcticMerge(plotTypes, centerX, edgeY, southEdge, contactDist, startOffset, hasWaterPath, numRidges, iW, iH, wrapX, wrapY)
	local inlandSeaY = getTundraLatitudeY(iH, southEdge);
	local startY = southEdge and startOffset or (edgeY - startOffset);
	local endY = southEdge and math.min(contactDist + 2, iH - 1) or math.max(0, edgeY - contactDist - 2);

	local width = 8 + Map.Rand(5, "");
	local landTiles = {};
	local ridgeTiles = {};
	local waterPathTiles = {};
	local seaTiles = {};

	local splinterChance = 25;
	local ridge1Gaps = {};
	local ridge2Gaps = {};

	for row = 0, math.abs(endY - startY) do
		local rowY = southEdge and (startY + row) or (startY - row);
		if rowY < 0 or rowY >= iH then break; end
		local half = math.floor(width / 2);
		for dx = -half, half do
			local x = centerX + dx;
			if wrapX then x = ((x % iW) + iW) % iW; end
			if x >= 0 and x < iW then landTiles[#landTiles + 1] = {x, rowY}; end
		end
	end

	local landSet = {};
	for _, t in ipairs(landTiles) do landSet[t[1] .. "," .. t[2]] = true; end

	for row = 0, math.abs(endY - startY) do
		local rowY = southEdge and (startY + row) or (startY - row);
		if rowY < 0 or rowY >= iH then break; end
		local half = math.floor(width / 2);
		local vSpread = math.floor(half * 0.15 * (row + 1));
		local ridge1X = centerX - math.floor(half * 0.35) - vSpread;
		local ridge2X = centerX + math.floor(half * 0.35) + vSpread;
		if Map.Rand(100, "") < splinterChance then ridge1Gaps[row] = true; end
		if Map.Rand(100, "") < splinterChance then ridge2Gaps[row] = true; end
		if not ridge1Gaps[row] then
			local rx = wrapX and (((ridge1X % iW) + iW) % iW) or ridge1X;
			if rx >= 0 and rx < iW and landSet[rx .. "," .. rowY] then ridgeTiles[#ridgeTiles + 1] = {rx, rowY}; end
		end
		if numRidges >= 2 and not ridge2Gaps[row] then
			local rx = wrapX and (((ridge2X % iW) + iW) % iW) or ridge2X;
			if rx >= 0 and rx < iW and landSet[rx .. "," .. rowY] then ridgeTiles[#ridgeTiles + 1] = {rx, rowY}; end
		end
		if hasWaterPath then
			local pathX = wrapX and (((centerX % iW) + iW) % iW) or centerX;
			if pathX >= 0 and pathX < iW and landSet[pathX .. "," .. rowY] then waterPathTiles[#waterPathTiles + 1] = {pathX, rowY}; end
		end
	end

	local seaSize = 4 + Map.Rand(9, "");
	local seaRadius = math.max(1, math.floor(math.sqrt(seaSize / 3.14)));
	local seaCenterX = centerX;
	local yLo, yHi = math.min(startY, endY), math.max(startY, endY);
	local seaCenterY = math.max(yLo + 1, math.min(inlandSeaY, yHi - 1));
	if wrapX then seaCenterX = (((seaCenterX % iW) + iW) % iW); end

	for dy2 = -seaRadius, seaRadius do
		for dx2 = -seaRadius, seaRadius do
			if dx2 * dx2 + dy2 * dy2 <= seaRadius * seaRadius then
				local sx = seaCenterX + dx2;
				if wrapX then sx = (((sx % iW) + iW) % iW); end
				local sy = seaCenterY + dy2;
				if sx >= 0 and sx < iW and sy >= 0 and sy < iH and sy >= startY and (southEdge and sy <= endY or not southEdge and sy >= endY) then
					seaTiles[#seaTiles + 1] = {sx, sy};
				end
			end
		end
	end

	local landSet2 = {};
	for _, t in ipairs(landTiles) do landSet2[t[1] .. "," .. t[2]] = true; end
	local waterPathSet = {};
	for _, t in ipairs(waterPathTiles) do waterPathSet[t[1] .. "," .. t[2]] = true; end
	local seaSet = {};
	for _, t in ipairs(seaTiles) do
		seaSet[t[1] .. "," .. t[2]] = true;
		landSet2[t[1] .. "," .. t[2]] = nil;
	end

	local ridgeSet = {};
	for _, t in ipairs(ridgeTiles) do ridgeSet[t[1] .. "," .. t[2]] = true; end

	local mountainPicks = {};
	for i = 1, #ridgeTiles do mountainPicks[i] = i; end
	for i = #mountainPicks, 2, -1 do
		local j = Map.Rand(i, "") + 1;
		mountainPicks[i], mountainPicks[j] = mountainPicks[j], mountainPicks[i];
	end
	local numMountains = math.min(#ridgeTiles, 2 + Map.Rand(math.max(1, #ridgeTiles), ""));
	for i = 1, numMountains do
		local t = ridgeTiles[mountainPicks[i]];
		ridgeSet[t[1] .. "," .. t[2]] = "mountain";
	end

	local islandInSea = {};
	if seaSize >= 10 and Map.Rand(100, "") < 50 then
		local candidates = {};
		for _, t in ipairs(seaTiles) do
			local x, y = t[1], t[2];
			local adjWater = 0;
			for dir = 1, 6 do
				local nx, ny = GetHexNeighbor(x, y, dir, iW, iH, wrapX, wrapY);
				if seaSet[nx .. "," .. ny] then adjWater = adjWater + 1; end
			end
			if adjWater >= 4 then candidates[#candidates + 1] = t; end
		end
		if #candidates > 0 then
			local pick = candidates[Map.Rand(#candidates, "") + 1];
			islandInSea[pick[1] .. "," .. pick[2]] = true;
		end
	end

	local function adjToMountain(x, y)
		for dir = 1, 6 do
			local nx, ny = GetHexNeighbor(x, y, dir, iW, iH, wrapX, wrapY);
			if ridgeSet[nx .. "," .. ny] == "mountain" then return true; end
		end
		return false;
	end

	if Map.Rand(100, "") < 25 then
		for _ = 1, 1 + Map.Rand(3, "") do
			local lx = centerX + (Map.Rand(5, "") - 2);
			if wrapX then lx = (((lx % iW) + iW) % iW); end
			local ly = southEdge and Map.Rand(2, "") or (edgeY - Map.Rand(2, ""));
			if lx >= 0 and lx < iW and ly >= 0 and ly < iH then
				landTiles[#landTiles + 1] = {lx, ly};
				landSet2[lx .. "," .. ly] = true;
			end
		end
	end

	for _, t in ipairs(landTiles) do
		local x, y = t[1], t[2];
		local idx = y * iW + x;
		if seaSet[x .. "," .. y] and not islandInSea[x .. "," .. y] then
			plotTypes[idx] = PlotTypes.PLOT_OCEAN;
		elseif waterPathSet[x .. "," .. y] then
			plotTypes[idx] = PlotTypes.PLOT_OCEAN;
		elseif islandInSea[x .. "," .. y] then
			plotTypes[idx] = (Map.Rand(100, "") < 50) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND;
		elseif ridgeSet[x .. "," .. y] == "mountain" then
			plotTypes[idx] = PlotTypes.PLOT_MOUNTAIN;
		elseif adjToMountain(x, y) then
			plotTypes[idx] = (Map.Rand(100, "") < HILLS_ADJ) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND;
		else
			plotTypes[idx] = (Map.Rand(100, "") < 50) and PlotTypes.PLOT_HILLS or PlotTypes.PLOT_LAND;
		end
	end
end
--]==]

------------------------------------------------------------------------------
-- ENTRY POINT
------------------------------------------------------------------------------
function TryPlacePolarMerge(plotTypes, opts)
	if _island_placed and _island_placed.polarmerge then return false; end
	local iW, iH = opts.iW, opts.iH;
	local wrapX = opts.wrapX or true;
	local wrapY = opts.wrapY or false;
	if wrapY then return false; end

	if Map.Rand(100, "") < CONFIG.EMBRACE_ODDS then
		if drawPangaeaEmbrace(plotTypes, iW, iH, wrapX, wrapY) then
			if not _island_placed then _island_placed = {}; end
			_island_placed.polarmerge = true;
			return true;
		end
	end
	return false;
end
